project:
  type: book
  output-dir: docs

execute:
  # cache: true
  # freeze: auto # only changed files are re-executed
  freeze: false # only changed files are re-executed

book:
  title: "Spatial Data Visualization with tmap"
  subtitle: "A Practical Guide to Thematic Mapping in R"
  page-footer: "Spatial Data Visualization with tmap: A Practical Guide to Thematic Mapping in R by Martijn Tennekes and Jakub Nowosad."
  # number-sections: true
  author: 
    - "Martijn Tennekes"
    - "Jakub Nowosad"
  description: | 
    "Spatial Data Visualization with tmap: A Practical Guide to Thematic Mapping in R" is a free, 
    open-source book that teaches you how to create static and interactive maps using the tmap package in R.
    Covering core concepts in thematic cartography, map design, and spatial visualization, this guide provides
    step-by-step approaches to help you produce high-quality maps for reports, presentations, and web applications.
  cover-image: images/cover_tmp_all_mockup.png
  site-url: https://tmap.geocompx.org/
  repo-url: https://github.com/geocompx/tmap/
  date: now
  date-format: iso
  repo-branch: main
  repo-actions: [edit]
  # sharing: [twitter, facebook, linkedin]
  google-analytics: G-ER2GMPEJNF
  # favicon: favicon-32x32.png
  chapters:
    - "index.qmd"
    - part: "Basics"
      chapters: 
        - "intro.qmd"
        - "geodata.qmd" 
        - "nutshell.qmd" 
        - "save.qmd" 
    - part: "Building blocks"
      chapters: 
        - "tm-shape.qmd" 
        - "layers.qmd" 
        - "visual-variables.qmd" 
        - "scales.qmd"
        - "legends.qmd"
        - "map-components.qmd"
        - "positions.qmd"
        - "layout.qmd" 
    - part: "Expanding the toolbox"
      chapters:
        - "map-projections.qmd"
        - "charts.qmd"
        - "arrangements.qmd"
        - "facets.qmd"
        - "animations.qmd"
        # - "basic-modes.qmd"
        - "interactive.qmd" 
    - part: "Advanced topics"
      chapters:
        - "options.qmd"
        - "shiny.qmd"
        #- "extended-modes.qmd"
        - "creating-extensions.qmd"
    - part: "Good practices"
      chapters:
        - "good-maps.qmd"
    - "references.qmd"
  appendices:
    - "data-processing.qmd"
    - "glossary.qmd"

format:
  html: 
    theme: [brand, flatly]
    # linkcolor: "#73A7A8"
    code-link: true
    template-partials: [helpers/toc.html, helpers/title-block.html]
    toc-title: "On this page"
    code-overflow: wrap
    toc-depth: 4
    # css: [helpers/mystyle.css]
  # pdf: #note--simplify authors list before rendering pdf
  #   documentclass: krantz
  #   monofont: 'Source Code Pro'
  #   monofontoptions: 
  #     - Scale=0.7
  #   pdf-engine: xelatex
  #   keep-tex: true
  #   number-sections: true
  #   top-level-division: chapter
  #   include-before-body: helpers/before_body.tex
  #   include-in-header: 
  #     text: |
  #       \AtBeginEnvironment{longtable}{\footnotesize}
  #       \usepackage{makeidx}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex

bibliography: 
  - r-tmap.bib
  - packages.bib
