```{r animations-1}
#| echo: false
source("code/before_script.R")
```

# Animations {#sec-animations}

<!-- tmap animations are a set of raster graphic images stitched together -->

```{r animations-2}
#| message: false
library(sf)
library(tmap)
slo_borders = read_sf("data/slovenia/slo_border.gpkg")
slo_regions_ts = read_sf("data/slovenia/slo_regions_ts.gpkg")
```

## Creating animations

```{r animations-3}
tm = tm_shape(slo_borders) +
  tm_borders() +
  tm_shape(slo_regions_ts) +
  tm_polygons("gdppercap")
```

```{r animations-4}
tm +
  tm_animate(by = "time")
```

```{r animations-5}
tm +
  tm_animate_fast(by = "time")
```

```{r animations-6}
tm +
  tm_animate(by = "time", fps = 5, play = "pingpong")
```


```{r animations-7}
#| message: false
library(stars)
slo_tavg = read_stars("data/slovenia/slo_tavg.tif")
```

```{r animations-8}
tm_shape(slo_tavg) +
  tm_raster(col.scale = tm_scale_continuous()) +
  tm_animate(by = "band", fps = 6)
```

<!-- passing other arguments to tm_facets (+ ref) -->

## Saving animations

```{r animations-9}
tma1 = tm +
  tm_animate_fast(by = "time")
```

```{r animations-10}
#| eval: false
tmap_animation(tma1, "tma1.gif")
```

<!-- width/height/dpi, scale -->
<!-- also ref to tmap_save -->
