```{r arrangements-1}
#| echo: false
source("code/before_script.R")
```

# Arranging maps {#sec-arranging-maps}


```{r arrangements-2}
library(tmap)
```

```{r arrangements-3}
#| message: false
library(sf)
slo_regions = read_sf("data/slovenia/slo_regions.gpkg")
tm1 = tm_shape(slo_regions) +
  tm_fill("gdppercap") +
  tm_borders() +
  tm_title("GDP per capita in Slovenia")
```

```{r arrangements-4}
#| message: false
library(stars)
slo_elev = read_stars("data/slovenia/slo_elev.tif")
tm2 = tm_shape(slo_elev) +
  tm_raster() +
  tm_borders() +
  tm_title("Elevation in Slovenia")
```

<!-- nrow, -->
<!-- ncol -->
<!-- asp -->

```{r}
#| label: fig-arrangements1
#| fig-cap: "Arranging two maps in one layout."
#| message: false
#| fig-asp: 0.8
tmap_arrange(tm1, tm2, ncol = 2)
```

<!-- frame alighnment -->

<!-- tmap_grob? -->

<!-- widths, heights -->
<!-- any better example idea? -->

```{r arrangements-6}
tmap_arrange(tm1, tm2, nrow = 2, heights = c(0.8, 0.2))
```

<!-- reexplain asp -->

<!-- possibly add a tm_add_legend example plus a ref -->

<!-- tmap view mode (sync) -->
<!-- tmap_save -->
