```{r facets-1}
#| echo: false
source("code/before_script.R")
```

# Facets {#sec-facets}
<!-- small-multiples -->

```{r facets-2}
#| message: false
library(sf)
library(tmap)
slo_borders = read_sf("data/slovenia/slo_border.gpkg")
slo_regions = read_sf("data/slovenia/slo_regions.gpkg")
slo_regions_ts = read_sf("data/slovenia/slo_regions_ts.gpkg")
slo_regions_ts = subset(slo_regions_ts, time %in% c("2006", "2010", "2014", "2018", "2022"))
```

<!-- tm_facets() -->
<!-- two approaches -- variables (e.g., columns) vs values in one variable -->
<!-- + a mix of both approaches -->
<!-- should we limit to e.g., 5 years? -->

## Specifying facets

```{r}
#| label: fig-facets1
#| fig-cap: "Facets for different variables."
#| fig-asp: 0.5
tm_shape(slo_regions) +
  tm_polygons(c("pop_dens", "gdppercap", "tourism"))
```

```{r}
#| label: fig-facets2
#| fig-cap: "Facets for one variable over time."
#| fig-asp: 0.4
tm_shape(slo_regions_ts) +
  tm_polygons("gdppercap") +
  tm_facets(by = "time", ncol = 5)
```

```{r}
#| label: fig-facets3
#| fig-cap: "Facets for multiple variables over time."
#| fig-asp: 1.2
tm_shape(slo_regions_ts) +
  tm_polygons(c("pop_dens", "gdppercap", "tourism")) +
  tm_facets(by = "time")
```

## Imporance of layers order

<!-- customize -->
```{r}
#| label: fig-facets4
#| fig-cap: "Facets for one variable for different region groups."
#| fig-asp: 0.4
tm_shape(slo_borders) +
  tm_borders() +
  tm_shape(slo_regions_ts) +
  tm_polygons("gdppercap") +
  tm_facets(by = "region_group", nrow = 2)
```

```{r}
#| label: fig-facets5
#| fig-cap: "Facets for one variable limiting the view to a specific region group."
tm_shape(slo_regions_ts) +
  tm_polygons("gdppercap") +
  tm_facets(by = "region_group", nrow = 2) +
  tm_shape(slo_borders) +
  tm_borders()
```

<!-- free.coords = FALSE) -->

```{r}
#| eval: false
#| label: fig-facets6
#| fig-cap: "Facets for one variable with free coordinates."
tm_shape(slo_regions_ts) +
  tm_polygons("gdppercap") +
  tm_facets(by = "region_group", nrow = 2, free.coords = FALSE) +
  tm_shape(slo_borders) +
  tm_borders()
```

## Facets types

<!-- other facets functions -->
<!-- tm_facets_wrap(by = "VARS__", nrow = NA, ncol = NA, byrow = TRUE, ...) -->
<!-- tm_facets_grid(rows = NULL, columns = NULL, pages = NULL, ...) -->

```{r}
#| label: fig-facets7
#| fig-cap: "Facets for one variable with wrapping."
#| fig-asp: 0.4
tm_shape(slo_borders) +
  tm_borders() +
  tm_shape(slo_regions_ts) +
  tm_polygons("gdppercap") +
  tm_facets_wrap(by = "region_group", nrow = 2)
```

```{r}
#| label: fig-facets8
#| fig-cap: "Two-dimensional facets for one variable in various region groups over time."
#| fig-asp: 0.7
tm_shape(slo_borders) +
  tm_borders() +
  tm_shape(slo_regions_ts) +
  tm_polygons("gdppercap") +
  tm_facets_grid(rows = "region_group", columns = "time")
```

<!-- also: https://r-tmap.github.io/tmap/articles/adv_multivariate -->

<!-- mention the rest -->
<!-- tm_facets_stack(by = "VARS__", orientation = NA, ...) -->
<!-- tm_facets_hstack(by = "VARS__", ...) -->
<!-- tm_facets_vstack(by = "VARS__", ...) -->
<!-- tm_facets_pagewise(by = "VARS__", byrow = TRUE, ...) -->
<!-- tm_facets_flip(...) -->

## Customizing facets

<!-- tm_xlab and tm_ylab for better labels -->
```{r}
#| label: fig-facets9
#| fig-cap: "Two-dimensional facets with labeled axes."
#| fig-asp: 0.7
tm_shape(slo_borders) +
  tm_borders() +
  tm_shape(slo_regions_ts) +
  tm_polygons("gdppercap") +
  tm_facets_grid(rows = "region_group", columns = "time") +
  tm_xlab("Year", side = "top", size = 2, space = 1) +
  tm_ylab("Region", rotation = 90, size = 2, space = 1)
```


<!-- Raster data -- where to add it in this section: either mix with the other content or after it -->
<!-- show how to add colors independently to each raster panel -->

```{r}
#| message: false
library(stars)
slo_tavg = read_stars("data/slovenia/slo_tavg.tif")
slo_elev = read_stars("data/slovenia/slo_elev.tif")
```

```{r}
#| label: fig-facets10
#| fig-cap: "Facets for raster data."
#| message: false
#| fig.asp: 1.1
tm_shape(slo_tavg) +
  tm_raster() +
  tm_facets(by = "band", ncol = 3) +
  tm_layout(panel.labels = c(1:12))
```

```{r}
#| label: fig-facets11
#| fig-cap: "Facets for raster data independent legends."
#| message: false
#| fig.asp: 1.1
tm_shape(slo_tavg) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"),
    col.legend = tm_legend(title = ""),
    col.free = TRUE) +
  tm_facets(by = "band", ncol = 3) +
  tm_layout(panel.labels = c(1:12)) +
  tm_title("Average monthly temperature in Slovenia") 
```

<!-- mixing with vector data -->

```{r}
#| label: fig-facets12
#| fig-cap: "Facets with raster data and vector data."
#| message: false
tm_shape(slo_elev) +
  tm_raster() +
  tm_shape(slo_regions, is.main = TRUE) + 
  tm_borders() +
  tm_facets(by = "region_group", free.coords = TRUE)
```

```{r facets-16}
#| eval: false
#| echo: false
tm_shape(slo_regions, is.main = TRUE) + 
  tm_borders() +
  tm_facets(by = "region_group", free.coords = TRUE) +
  tm_shape(slo_elev) +
  tm_raster()
```
