<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="“Spatial Data Visualization with tmap: A Practical Guide to Thematic Mapping in R” is a free, open-source book that teaches you how to create static and interactive maps using the tmap package in R. Covering core concepts in thematic cartography, map design, and spatial visualization, this guide provides step-by-step approaches to help you produce high-quality maps for reports, presentations, and web applications.">
<title>2&nbsp; Spatial data in R – Spatial Data Visualization with tmap</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./nutshell.html" rel="next">
<link href="./intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d5924b61622d6ff44928ab27c08a13e5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ER2GMPEJNF"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-ER2GMPEJNF', { 'anonymize_ip': true});
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./intro.html">Basics</a></li><li class="breadcrumb-item"><a href="./geodata.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Spatial data in R</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Spatial Data Visualization with tmap</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/geocompx/tmap/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Basics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./geodata.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Spatial data in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nutshell.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><strong>tmap</strong> in a nutshell</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./save.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Save maps</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Building blocks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tm-shape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Specifying spatial data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./layers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Layers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visual-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Visual variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Scales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./legends.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Legends and titles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./map-components.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Map components</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./positions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Positions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./layout.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Map layout</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Expanding the toolbox</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./map-projections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Map projections (CRS)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./charts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Charts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./arrangements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Arranging maps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./facets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Facets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./animations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Animations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interactive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Interactive settings</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./options.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">tmap options</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./shiny.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title"><strong>tmap</strong> in <strong>shiny</strong></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./creating-extensions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Creating extensions</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Good practices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./good-maps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">How to make good maps?</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Data preparation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Glossary</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 class="anchored">Work in Progress</h2>
  <ul>
<li><a href="https://geocompx.org/" class="nav-link active" data-scroll-target="https\://geocompx.org/">Visit the geocompx website 🌐</a></li>
    <li><a href="https://github.com/geocompx/tmap/issues" class="nav-link" data-scroll-target="https\://github.com/geocompx/tmap/issues">Open an issue ❔</a></li>
    <li><a href="https://discord.gg/PMztXYgNxp" class="nav-link" data-scroll-target="https\://discord.gg/PMztXYgNxp">Chat on Discord 📣</a></li>
  </ul>
<hr>
<h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#sec-intro-geodata" id="toc-sec-intro-geodata" class="nav-link" data-scroll-target="#sec-intro-geodata"><span class="header-section-number">2.1</span> Introduction</a></li>
  <li>
<a href="#sec-data-models" id="toc-sec-data-models" class="nav-link" data-scroll-target="#sec-data-models"><span class="header-section-number">2.2</span> Data models</a>
  <ul>
<li><a href="#sec-vector-data-model" id="toc-sec-vector-data-model" class="nav-link" data-scroll-target="#sec-vector-data-model"><span class="header-section-number">2.2.1</span> Vector data model</a></li>
  <li><a href="#sec-raster-data-model" id="toc-sec-raster-data-model" class="nav-link" data-scroll-target="#sec-raster-data-model"><span class="header-section-number">2.2.2</span> Raster data model</a></li>
  <li><a href="#sec-spatial-data-cubes" id="toc-sec-spatial-data-cubes" class="nav-link" data-scroll-target="#sec-spatial-data-cubes"><span class="header-section-number">2.2.3</span> Spatial data cubes</a></li>
  </ul>
</li>
  <li>
<a href="#sec-spatial-data-representations-in-r" id="toc-sec-spatial-data-representations-in-r" class="nav-link" data-scroll-target="#sec-spatial-data-representations-in-r"><span class="header-section-number">2.3</span> Spatial data representations in R</a>
  <ul>
<li><a href="#sec-the-sf-package" id="toc-sec-the-sf-package" class="nav-link" data-scroll-target="#sec-the-sf-package"><span class="header-section-number">2.3.1</span> The sf package</a></li>
  <li><a href="#sec-the-terra-package" id="toc-sec-the-terra-package" class="nav-link" data-scroll-target="#sec-the-terra-package"><span class="header-section-number">2.3.2</span> The terra package</a></li>
  <li><a href="#sec-the-stars-package" id="toc-sec-the-stars-package" class="nav-link" data-scroll-target="#sec-the-stars-package"><span class="header-section-number">2.3.3</span> The stars package</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/geocompx/tmap/edit/main/geodata.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./intro.html">Basics</a></li><li class="breadcrumb-item"><a href="./geodata.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Spatial data in R</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-geodata" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Spatial data in R</span></span></h1>
</div>

<!--
-->


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><!-- # Geographic data in R {#geodata} --><!-- to discuss --><p></p>
<section id="sec-intro-geodata" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="sec-intro-geodata">
<span class="header-section-number">2.1</span> Introduction</h2>
<p>Vector and raster data models are two basic models used to represent spatial data. These spatial data models are closely related to map making, with each model having its own pros and cons. <!-- - few introduction sections --> <!-- - mention GDAL, PROJ, and GEOS --> <!-- - maybe also mention some data sources --> This chapter stars by describing several popular spatial data models (<a href="#sec-data-models" class="quarto-xref"><span>Section 2.2</span></a>). Each data model is introduced, explained how it is built, and how it is stored using different file formats. Next, this chapter presents how these different data models are implemented in R (<a href="#sec-spatial-data-representations-in-r" class="quarto-xref"><span>Section 2.3</span></a>). It includes showing how to read different spatial data formats, how to understand spatial R objects, and where to find more information about preprocessing spatial data. Finally, it focuses on the map projections (<span class="quarto-unresolved-ref">?sec-crs</span>). This section gives a background on why do we need map projections and how to translate spatial data from an ellipsoid into a flat surface or computer screen. It also explains basic terms and gives an overview of map projections. <!-- - maybe also references to some books (either here or in the next section or both) --> <!-- geocompr, spatial data science, some crs book? --> <!-- explain that often there is a need to prepare spatial data before mapping --></p>
</section><section id="sec-data-models" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="sec-data-models">
<span class="header-section-number">2.2</span> Data models</h2>
<p>Traditionally, spatial data is described by two basic data models: vector data model aimed at (<a href="#sec-vector-data-model" class="quarto-xref"><span>Section 2.2.1</span></a>) representing the world using points, lines, and polygons, and raster data model focused on representing surfaces (<a href="#sec-raster-data-model" class="quarto-xref"><span>Section 2.2.2</span></a>). Additionally, now we have an abundance of available spatial data and a variety of ways to obtain it. It includes having many district variables and repeated measurements for the same area. Therefore, we also present the concept of spatial data cubes (<a href="#sec-spatial-data-cubes" class="quarto-xref"><span>Section 2.2.3</span></a>).</p>
<section id="sec-vector-data-model" class="level3" data-number="2.2.1"><h3 data-number="2.2.1" class="anchored" data-anchor-id="sec-vector-data-model">
<span class="header-section-number">2.2.1</span> Vector data model</h3>
<p> The vector data model represent the world as a set of spatial geometries with non-spatial attributes (<a href="#fig-vector-data-model" class="quarto-xref">Figure&nbsp;<span>2.1</span></a>). The role of geometry is to describe the location and shape of spatial objects. Attributes, on the other hand, are used to store the properties of the data.</p>
<p> There are three basic types of geometries: points, lines, and polygons, all of them are made up of coordinates (left part of <a href="#fig-vector-data-model" class="quarto-xref">Figure&nbsp;<span>2.1</span></a>). A point is represented by a pair of coordinates, usually described as X and Y, allowing for locating this point in some space. X and Y could be unitless, in degrees, or in some measure units, such as meters (extended discussion on coordinates and related topics is in section <span class="quarto-unresolved-ref">?sec-crs</span>). Points can represent features on different spatial scales, from a GPS position, location of a bench in a park, to a city on a small scale map. They are also used to express abstract features, such as locations of map labels. Properties of points<!--,such as ...--> can be expressed on maps by different point sizes, colors, or shapes<!--(markers/images) -->. A line extends the idea of a point. It consists of several points with coordinates (called vertices) that are arranged in some order. Consecutive points are connected by straight lines. Therefore, a straight spatial line consists of two points (two pairs of coordinates), while complex spatial lines could be created based on a large number of points.<!--to rewrite--> It gives the illusion that the line is curved. Lines are used to representing linear features, such as roads, rivers, boundaries, footpaths, etc. In this case, we can express line features’ attributes using either lines’ color or their widths. <!-- ways to adjust lines aesthetics: colors, lwd (line width) --> <!-- in theory lty could be also used - but it is not implemented in tmap --> A polygon is again a set of ordered points (vertices) connected by straight lines. Its only difference from the line is that the first and the last point in a polygon has the same coordinates, and thus close the object. <!-- examples of polygons --> The polygon representation is used to represent shapes and locations of different objects, from a lake or a patch of vegetation, through a building or a city block, to some administrative units. Polygons also have one unique feature - they could have holes. A polygon hole represents an area inside of the polygon but does not belong to it. For example, a lake with an island can be depicted as a polygon with a hole. The values of polygons’ attributes can be represented by the areas (fill) colors.</p>
<p> The second part of the vector data model relates to non-spatial attributes (right part of <a href="#fig-vector-data-model" class="quarto-xref">Figure&nbsp;<span>2.1</span></a>). Attributes are usually stored as a table, in which each column depicts some property, such as an identification number, a name of a feature, or a value of some characteristic. Each row, on the other hand, relates to a single spatial geometry.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-vector-data-model" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-vector-data-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-vector-data-model-1.png" class="img-fluid figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vector-data-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Instances of spatial vector data model: POINTS, LINES, and POLYGONS.
</figcaption></figure>
</div>
</div>
</div>
<p> The above ideas could be implemented in many ways. <!--...--> Currently, <a href="http://portal.opengeospatial.org/files/?artifact_id=25355">the Simple Feature Access</a> seems to be the most widely used standard. In it, a feature is every object or concept that have spatial location or extent.</p>
<p>Simple feature standard makes a clear distinction between single- and multi-element features. We can have a POINT feature and a MULTIPOINT feature, and similarly LINESTRING and MULTILINESTRING, and POLYGON and MULTIPOLYGON. The main difference between single element features (such as POINT or POLYGON) and multi-element features (such as MULTIPOINT or MULTIPOLYGON) can be clearly seen by looking at attribute tables. For example, six points stored as POINT features fill six separate rows, while six points stored as just one MULTIPOINT feature occupy just one row. <!-- redundancy --> Examples of single- and multi-element features can be seen in <a href="#fig-vector-data-model" class="quarto-xref">Figure&nbsp;<span>2.1</span></a>. The top example shows point data represented as MULTIPOINT feature: although we have seven points (seven distinct pairs of coordinates), they are gathered into two groups, green and orange, which can be seen in the associated attribute table. The central example, on the other hand, uses single-element features, where each line geometry relates to one row in the attribute table. Finally, the bottom example again uses multi-element features, where the second feature (<code>Country B</code>) consist of two separate geometries. The simple feature standard also describes a number of additional geometry types, including Curve, Surface, or Triangle. Finally, GeometryCollection exists that contains all of the possible geometry types.</p>
<!-- JN: maybe too much information-->
<!-- simple features standard also defines possible topological rules -->
<p> A couple hundreds of file formats exist to store spatial vector data. One of the simplest ways to store spatial data is in the form of a text file (<code>.csv</code>) or as a spreadsheet (<code>.xls</code> or <code>.xlsx</code>). While it makes storing point data simple, with two columns representing coordinates, it is not easy to store more complex objects in this way. Text files are also not suitable for storing information about the coordinate reference system used (<span class="quarto-unresolved-ref">?sec-crs</span>). Historically, the shapefile format (<code>.shp</code>) developed by the ESRI company gained a lot of interest and become the most widely supported spatial vector file format. Despite its popularity, this format has a number of shortcomings, including the need to store several files, attribute names limited to ten characters, the ability to store up to 255 attributes and files up to 2GB, and many more. A fairly recent file format, OGC GeoPackage (<code>.gpkg</code>), was developed as an alternative. It is a single file database free from the limitation of the shapefile format. Other popular spatial vector file formats include GeoJSON (<code>.geojson</code>), GPX (<code>.gpx</code>), and KML (<code>.kml</code>). <!-- FlatGeobuf?? --> <!-- - advantages/disadvantages --></p>
</section><section id="sec-raster-data-model" class="level3" data-number="2.2.2"><h3 data-number="2.2.2" class="anchored" data-anchor-id="sec-raster-data-model">
<span class="header-section-number">2.2.2</span> Raster data model</h3>
<p> The raster data model represents the world using a continuous grid of cells<!--pixels-->, where each cell has a single associated value (<a href="#fig-raster-intro" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>). Depending on the type of values, we can distinguish continuous and categorical rasters. In continuous rasters, such as elevation or precipitation, values vary progressively. Categorical rasters, on the other hand, uses integer values to represent classes. Their examples include land cover or soil types maps. Raster data can also contain cells for which we do not know the value (<a href="#fig-raster-intro" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>). For example, data for this part of the area was not collected, or these locations are outside of our area of interest.</p>
<div id="fig-raster-intro" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-raster-intro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-raster-intro" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-raster-intro-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-raster-intro-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-raster-intro-1.png" class="img-fluid figure-img" data-ref-parent="fig-raster-intro" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-raster-intro-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Cell IDs
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-raster-intro" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-raster-intro-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-raster-intro-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-raster-intro-2.png" class="img-fluid figure-img" data-ref-parent="fig-raster-intro" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-raster-intro-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Cell values
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-raster-intro" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-raster-intro-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-raster-intro-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-raster-intro-3.png" class="img-fluid figure-img" data-ref-parent="fig-raster-intro" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-raster-intro-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) A raster map
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-raster-intro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Basic representations of the raster data model
</figcaption></figure>
</div>
<p> When we think about raster data, most of the time we are referring to regular grids (<a href="#fig-grid-types" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>). In regular grids, each cell has the same, constant size, and coordinates change from top to bottom and from left to right<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. <!-- I know it is a simplification--> Regular rasters can be transformed into rotated and sheared rasters (<a href="#fig-grid-types" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>). Rotated grids are the result of transforming both coordinated, <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> using the same rotation coefficients. Sheared grids are created when the rotation coefficients are not equal. Rectilinear grids, on the other hand, have orthogonal axes, but consist of rectangular cells with different sizes and shapes (<a href="#fig-grid-types" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>). In the last type of raster data grids, curvilinear grids, cells are cuboids of different sizes and shapes (<a href="#fig-grid-types" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>).</p>
<!-- Q:should the counting in the below figure start from bottom left? -->
<div id="fig-grid-types" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-grid-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-grid-types" style="flex-basis: 20.0%;justify-content: flex-start;">
<div id="fig-grid-types-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-grid-types-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-grid-types-1.png" class="img-fluid figure-img" data-ref-parent="fig-grid-types" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-grid-types-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Regular
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-grid-types" style="flex-basis: 20.0%;justify-content: flex-start;">
<div id="fig-grid-types-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-grid-types-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-grid-types-2.png" class="img-fluid figure-img" data-ref-parent="fig-grid-types" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-grid-types-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Rotated
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-grid-types" style="flex-basis: 20.0%;justify-content: flex-start;">
<div id="fig-grid-types-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-grid-types-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-grid-types-3.png" class="img-fluid figure-img" data-ref-parent="fig-grid-types" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-grid-types-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Sheared
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-grid-types" style="flex-basis: 20.0%;justify-content: flex-start;">
<div id="fig-grid-types-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-grid-types-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-grid-types-4.png" class="img-fluid figure-img" data-ref-parent="fig-grid-types" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-grid-types-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Rectilinear
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-grid-types" style="flex-basis: 20.0%;justify-content: flex-start;">
<div id="fig-grid-types-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-grid-types-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-grid-types-5.png" class="img-fluid figure-img" data-ref-parent="fig-grid-types" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-grid-types-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) Curvilinear
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grid-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Main types of raster data grids
</figcaption></figure>
</div>
<p>Contrary to spatial vector data, a basic raster data stores just one attribute. It is, however, possible to stack together many single rasters (also known as raster layers). This allows us to store and operate on many rasters having the same dimensions at the same time. Examples of multi-layer rasters include satellite imageries or temporal rasters. Satellite imageries usually consist of many bands (layers) for different wavelengths. The most basic bands, representing the colors red, green, and blue, can be connected together to create one composite image with true colors (<a href="#fig-rgb-raster" class="quarto-xref">Figure&nbsp;<span>2.4</span></a>). Temporal rasters store one attribute, but for many moments in time. <!-- + comparing different attributes for the same area --> Additional information about multi-layer rasters can be also found in <a href="#sec-spatial-data-cubes" class="quarto-xref"><span>Section 2.2.3</span></a>.</p>
<div id="fig-rgb-raster" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-rgb-raster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-rgb-raster" style="flex-basis: 25.0%;justify-content: flex-start;">
<div id="fig-rgb-raster-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-rgb-raster-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-rgb-raster-1.png" class="img-fluid figure-img" data-ref-parent="fig-rgb-raster" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-rgb-raster-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Red
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-rgb-raster" style="flex-basis: 25.0%;justify-content: flex-start;">
<div id="fig-rgb-raster-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-rgb-raster-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-rgb-raster-2.png" class="img-fluid figure-img" data-ref-parent="fig-rgb-raster" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-rgb-raster-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Green
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-rgb-raster" style="flex-basis: 25.0%;justify-content: flex-start;">
<div id="fig-rgb-raster-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-rgb-raster-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-rgb-raster-3.png" class="img-fluid figure-img" data-ref-parent="fig-rgb-raster" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-rgb-raster-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Blue
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-rgb-raster" style="flex-basis: 25.0%;justify-content: flex-start;">
<div id="fig-rgb-raster-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-rgb-raster-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-rgb-raster-4.png" class="img-fluid figure-img" data-ref-parent="fig-rgb-raster" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-rgb-raster-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Composite
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rgb-raster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4: Example of three satellite imagery bands: red, green, blue, and the composite image with true colors created using these three bands.
</figcaption></figure>
</div>
<p> Similarly to vector data, a large number of raster file formats exists. <!-- text files ?--> Currently, the GeoTIFF format (<code>.tif</code> or <code>.tiff</code>) is one of the most popular spatial raster formats. It is an extended image TIF format that stores spatial metadata (e.g., map projection) along the values. Another popular spatial raster formats include Arc ASCII (<code>.asc</code>) and ERDAS Imagine (<code>.img</code>). <!-- ncdf??? --></p>
</section><section id="sec-spatial-data-cubes" class="level3" data-number="2.2.3"><h3 data-number="2.2.3" class="anchored" data-anchor-id="sec-spatial-data-cubes">
<span class="header-section-number">2.2.3</span> Spatial data cubes</h3>
<p> Traditionally, spatial vector and raster data models refer to a unique set of locations. For example, each feature in a polygon dataset and each cell in a raster dataset refer to one specific area. However, to solve real-life problems, we need to store and operate on more complex data structures. It includes situations when we have many attributes, often for several moments in time.</p>
<p> Storing multiple attributes is not a problem for the vector data model, when an attribute table can have many columns. The question is how to extend the spatial vector data model to include measurements for many times. For example, let’s consider a polygon data with many attributes representing shares of land-use types for several years (<a href="#fig-vector-data-cubes" class="quarto-xref">Figure&nbsp;<span>2.5</span></a>). One approach would be to create a separate column for each variable in each year.<!--wide--><!--pros and cons--> Alternatively, we can have one column representing the year and one column for each attribute, however, this approach would require multiplying each geometry as many times as we have time stamps. <!--long--><!--pros and cons--> The third approach involves separating geometries from attributes, and where attributes for each moment are stored independently. The last idea is used in spatial vector data cubes (<a href="#sec-the-stars-package" class="quarto-xref"><span>Section 2.3.3</span></a>). An example of the spatial vector data cubes idea can be seen in <a href="#fig-vector-data-cubes" class="quarto-xref">Figure&nbsp;<span>2.5</span></a>. It consists of two elements: a geometry (MULTIPOLYGON) of provinces of the Netherlands and an array connected to it that stores shares of land-use types for several years.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-vector-data-cubes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-vector-data-cubes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-vector-data-cubes-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vector-data-cubes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.5: Vector data cube.
</figcaption></figure>
</div>
</div>
</div>
<p> A single raster dataset can store just one variable for a given area. To store several attributes, we can connect rasters representing different attributes for the same extent, creating multi-layer rasters (<a href="#sec-raster-data-model" class="quarto-xref"><span>Section 2.2.2</span></a>). Additionally, each of the aforementioned rasters can be collected for many moments in time, adding other layers to the data. <!--pros and cons--> The question here is how to efficiently store multi-layer raster data to understand what layers relate to which attribute and time. Similarly to spatial vector data cubes, we can think of separating spatial dimensions from non-spatial attributes and create spatial raster data cubes (<a href="#sec-the-stars-package" class="quarto-xref"><span>Section 2.3.3</span></a>). <a href="#fig-raster-data-cubes" class="quarto-xref">Figure&nbsp;<span>2.6</span></a> gives an example of a raster data cube. It consists of several single-layer rasters with the same spatial properties, such as resolution, extent, and CRS. These rasters are organized to store four-dimensions of the data: latitude, longitude, time, and attributes. It has values of three attributes for five moments in time in total.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-raster-data-cubes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-raster-data-cubes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="geodata_files/figure-html/fig-raster-data-cubes-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-raster-data-cubes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.6: Raster data cube.
</figcaption></figure>
</div>
</div>
</div>
<p>Spatial data cubes are suitable for many real-life applications. For example, time-series of climate measurements for several stations, demographic data on a country level gathered for many years, or satellite imageries over some period of time.</p>
<p> One way to create spatial data cubes is by connecting many independent vector or raster objects. <!-- mention it in the stars section? --> Second way is to read a spatial data cube from one of the file formats allowing for storing complex data. It includes formats such as NetCDF (<code>.nc</code>) and HDF (<code>.hdf</code>). <!-- spatial vector data cubes file formats? --></p>
<!-- converting between spatial vector data cube and spatial raster data cube -->
</section></section><section id="sec-spatial-data-representations-in-r" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="sec-spatial-data-representations-in-r">
<span class="header-section-number">2.3</span> Spatial data representations in R</h2>
<p> R has several packages aimed to represent spatial vector data. <!-- Recently, the **terra** package has been released containing a new vector data representation. --> For more than a decade, the <strong>sp</strong> package <!--REF--> was a standard of vector data representation in R. However, now this package is in the maintenance mode only, and its successor, <strong>sf</strong> is recommended. The <strong>tmap</strong> package has been using <strong>sf</strong> since version 2.0.</p>
<p> Several R packages can be used to represent spatial raster data, including <strong>raster</strong> and its successor <strong>terra</strong>. The <strong>raster</strong> package was used as a backbone of raster data visualization until <strong>tmap</strong> version 3.0. Nowadays, the <strong>stars</strong> package is used by <strong>tmap</strong> to operate on raster data and spatial data cubes.</p>
<p>In the two next sections, we introduce the <strong>sf</strong> package (<a href="#sec-the-sf-package" class="quarto-xref"><span>Section 2.3.1</span></a>) and the <strong>stars</strong> package (<a href="#sec-the-stars-package" class="quarto-xref"><span>Section 2.3.3</span></a>).</p>
<!-- spatial data cubes -->
<!-- https://github.com/appelmar/gdalcubes_R -->
<!-- https://ropensci.org/blog/2019/11/05/tidync/ -->
<section id="sec-the-sf-package" class="level3" data-number="2.3.1"><h3 data-number="2.3.1" class="anchored" data-anchor-id="sec-the-sf-package">
<span class="header-section-number">2.3.1</span> The sf package</h3>
<p> </p>
<p>The <strong>sf</strong> package implements ideas behind the Simple Feature standard, which describe how to represent spatial vector data. Its main class, <code>sf</code>, has the form of an extended data frame, where each row is a spatial feature. In it, attributes of the vector data are stored as columns. It also has one additional column, most often named <code>geom</code> or <code>geometry</code><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. This column contains geometries in a form of well-known text (WKT), storing all of the coordinates.</p>
<!-- - how to read sf objects from files -->
<p>The <strong>sf</strong> package can read all of the spatial data formats mentioned in <a href="#sec-vector-data-model" class="quarto-xref"><span>Section 2.2.1</span></a> using the <code><a href="https://r-spatial.github.io/sf/reference/st_read.html">read_sf()</a></code> function<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. <!--improve example--></p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span></span>
<span><span class="va">worldvector</span> <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">read_sf</a></span><span class="op">(</span><span class="st">"data/worldvector.gpkg"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The new object, <code>worldvector</code>, has a <code>sf</code> class. It has 185 features (rows or geometries) and 15 fields (columns with attributes). There is also an 16th column, <code>geom</code>, that stores geometries of each feature. Objects of class <code>sf</code> also display a header containing spatial metadata. It includes geometry type, dimension (<code>XY</code>, <code>XYZ</code>, <code>XYM</code>, <code>XYZM</code>), bounding box (<code>bbox</code>), and information about the used Coordinate Reference System (<code>CRS</code>).</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">worldvector</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 185 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -16331900 ymin: -8392908 xmax: 16886150 ymax: 8315884
Projected CRS: WGS 84 / Equal Earth Greenwich
# A tibble: 185 × 16
   GEO   name    wb_region wb_income_region population CO2_emissions gdp_per_cap
   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;                 &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;
 1 AUS   Austra… East Asi… High income        42900000       15.3          56800
 2 AZE   Azerba… Europe &amp;… Upper middle in…    9190000        3.94          5770
 3 BIH   Bosnia… Europe &amp;… Upper middle in…    1640000        6.38          6030
 4 BGD   Bangla… South As… Lower middle in…  151000000        0.474         1200
 5 BEL   Belgium Europe &amp;… High income        12500000        8.32         47200
 6 BFA   Burkin… Sub-Saha… Low income         83200000        0.162          712
 7 BGR   Bulgar… Europe &amp;… Upper middle in…    3590000        5.85          8650
 8 BDI   Burundi Sub-Saha… Low income         50900000        0.0447         211
 9 BEN   Benin   Sub-Saha… Low income         47200000        0.614          897
10 BRN   Brunei  East Asi… High income          390000       22.2          31400
# ℹ 175 more rows
# ℹ 9 more variables: life_expectancy &lt;dbl&gt;, corruption_perception_index &lt;dbl&gt;,
#   democracy_score &lt;dbl&gt;, hdi &lt;dbl&gt;, energy_use_per_cap &lt;dbl&gt;,
#   literacy_rate &lt;dbl&gt;, demo_corr &lt;dbl&gt;, demo_corr_rank &lt;int&gt;,
#   geom &lt;MULTIPOLYGON [m]&gt;</code></pre>
</div>
</div>
<p>The <code>worldvector</code> object has MULTIPOLYGON geometry type, where each feature (row) can consist of one or more polygons. Each polygon’s vertices are represented by a pair of values (<code>dimension: XY</code>). Bounding box allows to quickly understand the spatial extension of the input data. <!--...--> Finally, it has projected CRS named WGS 84 / Equal Earth Greenwich. You can learn more about Coordinate Reference Systems in <span class="quarto-unresolved-ref">?sec-crs</span>. <!-- ref to CRS section --></p>
<p>Spatial vector data of class <code>sf</code> can be also obtained using some of other R data packages. <!-- add REFs--> For example, <strong>rnaturalearth</strong> allows to download world map data, <strong>osmdata</strong> imports OpenStreetMap data as <code>sf</code> objects, and <strong>tigris</strong> loads TIGER/Line data. <!-- add reference to geocompr --> <!-- add reference to https://cran.r-project.org/web/views/Spatial.html (after my updates) --></p>
<p>The <strong>tmap</strong> package accepts spatial vector data objects from both <strong>sf</strong> and <strong>sp</strong> packages. In case of having vector objects in a different representation, they should be converted into <code>sf</code> objects first, before making maps. The <strong>sf</strong> package has the <code><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf()</a></code> function that translates objects of many classes, including <code>Spatial</code> (from the <strong>sp</strong> package), <code>ppp</code>, <code>psp</code>, and <code>lpp</code> (from the <strong>spatstat</strong> package), to the objects of class <code>sf</code>. The <code><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf()</a></code> function also allows to turn data frames into <code>sf</code> objects - the user needs to provide the input data frame, names of columns with coordinates, and additionally definition of the CRS of the data. For example <code>my_sf = st_as_sf(my_df, coords = c("Xcolumn", "Ycolumn"), crs = "EPSG:4326")</code>.</p>
<p>If you want to learn more about operating on <code>sf</code> objects, we recommend visiting the package website and vignettes at <a href="https://r-spatial.github.io/sf/" class="uri">https://r-spatial.github.io/sf/</a> and reading <a href="https://geocompr.github.io/">the Geocomputation with R book</a> <span class="citation" data-cites="lovelace_geocomputation_2025">(<a href="references.html#ref-lovelace_geocomputation_2025" role="doc-biblioref">Lovelace, Nowosad, and Muenchow 2025</a>)</span>. <!-- - vector simplification? --></p>
</section><section id="sec-the-terra-package" class="level3" data-number="2.3.2"><h3 data-number="2.3.2" class="anchored" data-anchor-id="sec-the-terra-package">
<span class="header-section-number">2.3.2</span> The terra package</h3>
<p> </p>
</section><section id="sec-the-stars-package" class="level3" data-number="2.3.3"><h3 data-number="2.3.3" class="anchored" data-anchor-id="sec-the-stars-package">
<span class="header-section-number">2.3.3</span> The stars package</h3>
<p> </p>
<!-- intro stars -->
<p>The <strong>stars</strong> package allows for reading and processing raster data in R. This package also has support for both spatial vector and raster data cubes. Its main class, <code>stars</code>, is built as a list of matrices or arrays with metadata describing their dimensions. The <strong>stars</strong> package is also well integrated with <strong>sf</strong>, with many <code>st_</code> functions (such as <code><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs()</a></code>) working also on <code>stars</code> objects.</p>
<!-- - how to read stars objects from files -->
<p>The <code><a href="https://r-spatial.github.io/stars/reference/read_stars.html">read_stars()</a></code> function allow to read spatial raster data from a file<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. This function requires at least one argument with a filename to be read. <!--improve example--></p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/stars/">stars</a></span><span class="op">)</span></span>
<span><span class="va">worldelevation</span> <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/stars/reference/read_stars.html">read_stars</a></span><span class="op">(</span><span class="st">"data/worldelevation.tif"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The new object, <code>worldelevation</code>, is of a <code>stars</code> class. It has two dimensions, <code>x</code> and <code>y</code>, and one attribute <code>worldelevation.tif</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">worldelevation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stars object with 2 dimensions and 1 attribute
attribute(s):
                    Min. 1st Qu. Median     Mean 3rd Qu. Max.   NA's
worldelevation.tif  -412     218    608 1139.982    1941 6410 389580
dimension(s):
  from   to offset   delta refsys point x/y
x    1 1080   -180  0.3333 WGS 84 FALSE [x]
y    1  540     90 -0.3333 WGS 84 FALSE [y]</code></pre>
</div>
</div>
<p>The <code>worldelevation.tif</code> attribute is a matrix, where each cell represents an elevation value. The <code>x</code> dimension has 1080 elements (columns), starting from a coordinate (<code>offset</code>) of a cell boundary of <code>-180</code>. Next, the coordinates of further cells increase by <code>0.333333</code> (<code>delta</code>) - resolution in the <code>x</code> dimension. The <code>y</code> dimension has 540 elements (rows), starting from a coordinate (<code>offset</code>) of a cell boundary of <code>90</code>. For the <code>y</code> dimension, each further cell’s coordinated decreases by <code>0.333333</code> (notice the negative value of <code>delta</code>) - resolution in the <code>y</code> dimension. Both dimensions also have the same CRS - <code>WGS 84</code>.</p>
<p><code><a href="https://r-spatial.github.io/stars/reference/read_stars.html">read_stars()</a></code> also has several additional arguments including <code>RasterIO</code>, which gives control over the input data extent and resolution. For example, the below code will read just the first and second bands (results not shown). <!-- - including reading chunks, changing resolution, and selecting bands --> <!--improve example--></p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">file_path3</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/system.file.html">system.file</a></span><span class="op">(</span><span class="st">"raster/landsat.tif"</span>, package <span class="op">=</span> <span class="st">"spDataLarge"</span><span class="op">)</span></span>
<span><span class="va">x3</span> <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/stars/reference/read_stars.html">read_stars</a></span><span class="op">(</span><span class="va">file_path3</span>, RasterIO <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>bands <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Internally, a <code>stars</code> object is a list of <code>matrix</code> or <code>array</code> objects with additional attributes describing spatial metadata, such as a number of columns and rows, resolution, coordinate reference system, etc. All of this information is read from the input file.</p>
<p>Stars objects are constructed by dimensions and attributes. Dimensions relate to what kind of objects are stored as list elements. For example, when it is a <code>matrix</code> then we just have two dimensions representing columns and rows. However, it is also possible to store multidimensional <code>array</code>s, which allow having many additional dimensions for bands, times, etc. Attributes, on the other hand, are stored as list elements. Each attribute can relate, for example to a different variable.</p>
<p>Reading a simple GeoTIFF file would result in having just two dimensions and one attribute (a <code>matrix</code>). On the other hand, reading complex raster file formats, such as NetCDF could result in having more than two dimensions (e.g.&nbsp;time) and many attributes (e.g., an <code>array</code> with temperature, precipitation, humidity). <!-- how it relates to mapping? --></p>
<!-- - stars proxy -->
<!-- more than 1e8 cells to read -->
<p>Before reading the file, the <strong>stars</strong> package checks if the input data is a curvilinear grid and what is the number of cells in the data. When the input data is small or curvilinear then the full data is read in computer memory. Otherwise, a <code>stars proxy</code> approach is used, where only metadata is read including pointers to where the complete data is. When we want to plot large raster data, then it is read at a lower resolution than the native one. <!-- ref to the section where we are explaining max.plot options --></p>
<p>The <strong>stars</strong> package also has support for vector data cubes, where each geometry is just stored once (as a dimension), and each attribute is a <code>matrix</code> or an <code>array</code> with the number of rows equals to the number of geometries, the number of columns equals to another dimension (e.g., time), and possibly the number of <code>array</code> layers equals for additional dimensions. <!-- can we plot them in tmap? --> <!-- if so - there should be an example in the book + reference --></p>
<!-- The **tmap** package accepts spatial raster data objects from both **stars** and **raster** packages. -->
<p>More information on how the <code>stars</code> objects are organized and how to operate on them can be found in the <strong>stars</strong> package vignettes at https://r-spatial.github.io/stars. <!-- - advice: sometimes/often it is better to prepare spatial object before the mapping, than trying to over-customize the map --></p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-lovelace_geocomputation_2025" class="csl-entry" role="listitem">
Lovelace, Robin, Jakub Nowosad, and Jannes Muenchow. 2025. <em>Geocomputation with <span>R</span></em>. Second. <span>CRC Press</span>.
</div>
</div>
</section></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>Regular grids can also have coordinated changing in different directions, e.g., from bottom to top.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>However, any other names are also possible.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>It is also possible to read spatial vector data using the <code><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read()</a></code> function, which differs from <code><a href="https://r-spatial.github.io/sf/reference/st_read.html">read_sf()</a></code> by having different default arguments.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The <strong>stars</strong> package also has a function <code><a href="https://r-spatial.github.io/stars/reference/read_ncdf.html">read_ncdf()</a></code> aimed at improved reading of NetCDF files.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/tmap\.geocompx\.org\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./intro.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./nutshell.html" class="pagination-link" aria-label="**tmap** in a nutshell">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><strong>tmap</strong> in a nutshell</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Spatial Data Visualization with tmap: A Practical Guide to Thematic Mapping in R by Martijn Tennekes and Jakub Nowosad.</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/geocompx/tmap/edit/main/geodata.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>