```{r}
#| echo: false
source("code/before_script.R")
```

# Positions {#sec-positions}

```{r}
#| message: false
library(sf)
library(stars)
library(tmap)
slo_elev = read_stars("data/slovenia/slo_elev.tif")
tm = tm_shape(slo_elev) +
    tm_raster()
```

## Positioning

<!-- idea: add figures inspired by https://r-tmap.github.io/tmap/articles/adv_positions#grouping-components but without the code itself -->

### Inside the map frame

```{r}
#| echo: false
boxy = function(text, fill) {
  grid::gList(
    grid::rectGrob(gp = grid::gpar(fill = "gold")), 
    # grid::circleGrob(r = .45), 
    grid::textGrob(text)
  )
}
g = \(text) boxy(text, fill = "gold")
b = \(text) boxy(text, fill = "steelblue")
```

```{r}
#| echo: false
#| message: false
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(show = FALSE)) +
    tm_inset(g('"left", "top"'), position = c("left", "top")) +
    tm_inset(g('"right", "bottom"'), position = c("right", "bottom")) +
    tm_inset(g('"LEFT", "BOTTOM"'), position = c("LEFT", "BOTTOM")) +
    tm_inset(g('"left", "center"'), position = c("left", "center")) +
    tm_inset(b('0.5, 0.5'), position = c(0.5, 0.5)) +
    tm_inset(b('0.6, 1'), position = c(0.6, 1))
```

```{r}
#| eval: false
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(position = c("right", "bottom")))
```

```{r}
#| eval: false
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(position = c("RIGHT", "BOTTOM")))
```

```{r}
#| eval: false
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(position = tm_pos_in("right", "bottom")))
```

```{r}
#| eval: false
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(position = tm_pos_in(0.8, 0.2)))
```

<!-- tm_pos_in() -- middle of a cell -->

### Outside the map frame

```{r}
#| echo: false
#| message: false
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(show = FALSE)) + 
    tm_inset(g('"center", "center"'), position = tm_pos_on_top(pos.h = "center", pos.v = "center")) +
    tm_inset(g('"left", "center"'), position = tm_pos_out("left", "center", pos.v = "center")) +
    tm_inset(g('"right", "center"'), position = tm_pos_out("right", "center", pos.v = "center")) +
    tm_inset(g('"left", "top"'), position = tm_pos_out("left", "top")) +
    tm_inset(g('"center", "top"'), position = tm_pos_out("center", "top", pos.h = "center")) +
    tm_inset(g('"right", "top"'), position = tm_pos_out("right", "top")) +
    tm_inset(g('"left", "bottom"'), position = tm_pos_out("left", "bottom")) +
    tm_inset(g('"center", "bottom"'), position = tm_pos_out("center", "bottom", pos.h = "center")) +
    tm_inset(g('"right", "bottom"'), position = tm_pos_out("right", "bottom")) +
    tm_layout(asp = 1, frame.lwd = 2)
```


```{r}
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(position = tm_pos_out("left", "center")))
```

```{r}
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(position = tm_pos_out("left", "center", pos.v = "center")))
```


```{r}
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(position = tm_pos_out("center", "center",
                                                           pos.h = "left", pos.v = "bottom")))
```


```{r}
#| echo: false
#| message: false
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(show = FALSE)) + 
    tm_inset(g("pos.v = \"top\" in\ncell (\"left\", \"center\")"), 
      position = tm_pos_out("left", "center", pos.v = "top")) +
    tm_inset(g("pos.v = \"bottom\" in\ncell (\"right\", \"center\")"), 
      position = tm_pos_out("right", "center", pos.v = "bottom")) +
    tm_inset(g("pos.h = \"center\" in\ncell (\"center\", \"top\")"), 
      position = tm_pos_out("center", "top", pos.h = "center")) +
    tm_inset(g("pos.h = \"right\" in\ncell (\"center\", \"bottom\")"), 
      position = tm_pos_out("center", "bottom", pos.h = "right")) +
    tm_layout(asp = 1, frame.lwd = 2)
```

```{r}
tm_shape(slo_elev) +
  tm_raster(col.legend = tm_legend(position = tm_pos_out("left", "center"))) +
  tm_scalebar(position = tm_pos_out("left", "center", pos.v = "bottom"))
```

```{r}
#| echo: false
#| message: false
tm_shape(slo_elev) +
    tm_raster(col.legend = tm_legend(show = FALSE)) +
    tm_inset(b("pos.h = 0.5\npos.v = 0.5\nin center cell"),
               position = tm_pos_in(pos.h = 0.5, pos.v = 0.5)) +
    tm_inset(b("pos.h = 0.5\npos.v = 0.5\nin center cell"),
               position = tm_pos_in(pos.h = 1, pos.v = 1,
                                    just.h = "right", just.v = "top")) +
    tm_inset(b("pos.h = 0.5\npos.v = 0.5\nin center cell"),
               position = tm_pos_in(pos.h = 0, pos.v = 0.5,
                                    just.h = "left", just.v = "center"))
```

```{r}
tm_shape(slo_elev) +
  tm_raster(col.legend = tm_legend(position = tm_pos_out("left", "center"))) +
  tm_scalebar(position = tm_pos_out("left", "center"))
```

```{r}
tm_shape(slo_elev) +
  tm_raster() +
  tm_scalebar() +
  tm_layout(component.position = tm_pos_out("left", "center"))
```

## Grouping

```{r}
tm_shape(slo_elev) +
  tm_raster(col.legend = tm_legend(group_id = 1)) +
  tm_scalebar(group_id = 2) +
  tm_credits("My credits", group_id = 2) +
  tm_comp_group(1, position = tm_pos_in("right", "bottom")) +
  tm_comp_group(2, position = tm_pos_in("left", "top"))
```

```{r}
tm_shape(slo_elev) +
  tm_raster(col.legend = tm_legend(group_id = 1)) +
  tm_scalebar(group_id = 2) +
  tm_credits("My credits", group_id = 2) +
  tm_comp_group(1, position = tm_pos_in("right", "bottom")) +
  tm_comp_group(2, position = tm_pos_in("left", "top"), stack = "horizontal")
```

<!-- z -- order -->
<!-- , frame_combine = FALSE -->
<!-- equalize = FALSE -->
<!-- , offset = 0, stack_margin = 1 -->
<!-- frame = TRUE, bg.color = "purple", bg.alpha = 0.5 -->