{
  "hash": "f8c136e5871049a9759106090dd93be8",
  "result": {
    "engine": "knitr",
    "markdown": "# Spatial data in R {#sec-geodata}\n<!-- # Geographic data in R {#geodata} -->\n<!-- to discuss -->\n\n\\index{spatial data}\n\n## Introduction {#sec-intro-geodata}\n\nVector and raster data models are two basic models used to represent spatial data.\nThese spatial data models are closely related to map making, with each model having its own pros and cons. \n<!-- - few introduction sections -->\n<!-- - mention GDAL, PROJ, and GEOS -->\n<!-- - maybe also mention some data sources -->\nThis chapter stars by describing several popular spatial data models (@sec-data-models).\nEach data model is introduced, explained how it is built, and how it is stored using different file formats.\nNext, this chapter presents how these different data models are implemented in R (@sec-spatial-data-representations-in-r).\nIt includes showing how to read different spatial data formats, how to understand spatial R objects, and where to find more information about preprocessing spatial data.\nFinally, it focuses on the map projections (@sec-crs).\nThis section gives a background on why do we need map projections and how to translate spatial data from an ellipsoid into a flat surface or computer screen.\nIt also explains basic terms and gives an overview of map projections.\n<!-- - maybe also references to some books (either here or in the next section or both) -->\n<!-- geocompr, spatial data science, some crs book? -->\n<!-- explain that often there is a need to prepare spatial data before mapping -->\n\n## Data models {#sec-data-models}\n\nTraditionally, spatial data is described by two basic data models: \nvector data model aimed at (@sec-vector-data-model) representing the world using points, lines, and polygons, and raster data model focused on representing surfaces (@sec-raster-data-model).\nAdditionally, now we have an abundance of available spatial data and a variety of ways to obtain it.\nIt includes having many district variables and repeated measurements for the same area.\nTherefore, we also present the concept of spatial data cubes (@sec-spatial-data-cubes).\n\n### Vector data model {#sec-vector-data-model}\n\n\\index{vector data model}\n\\index{spatial geometries}\n\\index{spatial attributes}\nThe vector data model represent the world as a set of spatial geometries with non-spatial attributes (@fig-vector-data-model). \nThe role of geometry is to describe the location and shape of spatial objects.\nAttributes, on the other hand, are used to store the properties of the data.\n\n\\index{spatial geometries}\nThere are three basic types of geometries: points, lines, and polygons, all of them are made up of coordinates (left part of @fig-vector-data-model).\nA point is represented by a pair of coordinates, usually described as X and Y, allowing for locating this point in some space.\nX and Y could be unitless, in degrees, or in some measure units, such as meters  (extended discussion on coordinates and related topics is in section @sec-crs).\nPoints can represent features on different spatial scales, from a GPS position, location of a bench in a park, to a city on a small scale map.\nThey are also used to express abstract features, such as locations of map labels.\nProperties of points<!--,such as ...--> can be expressed on maps by different point sizes, colors, or shapes<!--(markers/images) -->.\nA line extends the idea of a point.\nIt consists of several points with coordinates (called vertices) that are arranged in some order.\nConsecutive points are connected by straight lines.\nTherefore, a straight spatial line consists of two points (two pairs of coordinates), while complex spatial lines could be created based on a large number of points.<!--to rewrite-->\nIt gives the illusion that the line is curved. \nLines are used to representing linear features, such as roads, rivers, boundaries, footpaths, etc. \nIn this case, we can express line features' attributes using either lines' color or their widths.\n<!-- ways to adjust lines aesthetics: colors, lwd (line width) -->\n<!-- in theory lty could be also used - but it is not implemented in tmap -->\nA polygon is again a set of ordered points (vertices) connected by straight lines. \nIts only difference from the line is that the first and the last point in a polygon has the same coordinates, and thus close the object.\n<!-- examples of polygons -->\nThe polygon representation is used to represent shapes and locations of different objects, from a lake or a patch of vegetation, through a building or a city block, to some administrative units. \nPolygons also have one unique feature - they could have holes. \nA polygon hole represents an area inside of the polygon but does not belong to it.\nFor example, a lake with an island can be depicted as a polygon with a hole.\nThe values of polygons' attributes can be represented by the areas (fill) colors.\n\n\\index{spatial attributes}\nThe second part of the vector data model relates to non-spatial attributes (right part of @fig-vector-data-model). \nAttributes are usually stored as a table, in which each column depicts some property, such as an identification number, a name of a feature, or a value of some characteristic.\nEach row, on the other hand, relates to a single spatial geometry. \n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Instances of spatial vector data model: POINTS, LINES, and POLYGONS.](geodata_files/figure-html/fig-vector-data-model-1.png){#fig-vector-data-model width=480}\n:::\n:::\n\n\n\\index{simple feature}\nThe above ideas could be implemented in many ways. <!--...-->\nCurrently, [the Simple Feature Access](http://portal.opengeospatial.org/files/?artifact_id=25355) seems to be the most widely used standard.\nIn it, a feature is every object or concept that have spatial location or extent. \n\nSimple feature standard makes a clear distinction between single- and multi-element features.\nWe can have a POINT feature and a MULTIPOINT feature, and similarly LINESTRING and MULTILINESTRING, and POLYGON and MULTIPOLYGON.\nThe main difference between single element features (such as POINT or POLYGON) and multi-element features (such as MULTIPOINT or MULTIPOLYGON) can be clearly seen by looking at attribute tables. \nFor example, six points stored as POINT features fill six separate rows, while six points stored as just one MULTIPOINT feature occupy just one row.\n<!-- redundancy -->\nExamples of single- and multi-element features can be seen in @fig-vector-data-model. \nThe top example shows point data represented as MULTIPOINT feature: although we have seven points (seven distinct pairs of coordinates), they are gathered into two groups, green and orange, which can be seen in the associated attribute table.\nThe central example, on the other hand, uses single-element features, where each line geometry relates to one row in the attribute table.\nFinally, the bottom example again uses multi-element features, where the second feature (`Country B`) consist of two separate geometries.\nThe simple feature standard also describes a number of additional geometry types, including Curve, Surface, or Triangle.\nFinally, GeometryCollection exists that contains all of the possible geometry types.\n\n<!-- JN: maybe too much information-->\n<!-- simple features standard also defines possible topological rules -->\n\n\\index{spatial file formats}\nA couple hundreds of file formats exist to store spatial vector data.\nOne of the simplest ways to store spatial data is in the form of a text file (`.csv`) or as a spreadsheet (`.xls` or `.xlsx`). \nWhile it makes storing point data simple, with two columns representing coordinates, it is not easy to store more complex objects in this way.\nText files are also not suitable for storing information about the coordinate reference system used (@sec-crs).\nHistorically, the shapefile format (`.shp`) developed by the ESRI company gained a lot of interest and become the most widely supported spatial vector file format. \nDespite its popularity, this format has a number of shortcomings, including the need to store several files, attribute names limited to ten characters, the ability to store up to 255 attributes and files up to 2GB, and many more.\nA fairly recent file format, OGC GeoPackage (`.gpkg`), was developed as an alternative. \nIt is a single file database free from the limitation of the shapefile format.\nOther popular spatial vector file formats include GeoJSON (`.geojson`), GPX (`.gpx`), and KML (`.kml`). \n<!-- FlatGeobuf?? -->\n<!-- - advantages/disadvantages -->\n\n### Raster data model {#sec-raster-data-model}\n\n\\index{raster data model}\nThe raster data model represents the world using a continuous grid of cells<!--pixels-->, where each cell has a single associated value (@fig-raster-intro).\nDepending on the type of values, we can distinguish continuous and categorical rasters.\nIn continuous rasters, such as elevation or precipitation, values vary progressively.\nCategorical rasters, on the other hand, uses integer values to represent classes.\nTheir examples include land cover or soil types maps.\nRaster data can also contain cells for which we do not know the value (@fig-raster-intro).\nFor example, data for this part of the area was not collected, or these locations are outside of our area of interest.\n\n\n::: {#fig-raster-intro .cell layout-ncol=\"3\"}\n::: {.cell-output-display}\n![Cell IDs](geodata_files/figure-html/fig-raster-intro-1.png){#fig-raster-intro-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Cell values](geodata_files/figure-html/fig-raster-intro-2.png){#fig-raster-intro-2 width=672}\n:::\n\n::: {.cell-output-display}\n![A raster map](geodata_files/figure-html/fig-raster-intro-3.png){#fig-raster-intro-3 width=672}\n:::\n\nBasic representations of the raster data model\n:::\n\n\n\\index{raster data grid types}\nWhen we think about raster data, most of the time we are referring to regular grids (@fig-grid-types).\nIn regular grids, each cell has the same, constant size, and coordinates change from top to bottom and from left to right^[Regular grids can also have coordinated changing in different directions, e.g., from bottom to top.].\n<!-- I know it is a simplification-->\nRegular rasters can be transformed into rotated and sheared rasters (@fig-grid-types).\nRotated grids are the result of transforming both coordinated, $x$ and $y$ using the same rotation coefficients.\nSheared grids are created when the rotation coefficients are not equal.\nRectilinear grids, on the other hand, have orthogonal axes, but consist of rectangular cells with different sizes and shapes (@fig-grid-types).\nIn the last type of raster data grids, curvilinear grids, cells are cuboids of different sizes and shapes (@fig-grid-types).\n\n<!-- Q:should the counting in the below figure start from bottom left? -->\n\n::: {#fig-grid-types .cell layout-ncol=\"5\"}\n::: {.cell-output-display}\n![Regular](geodata_files/figure-html/fig-grid-types-1.png){#fig-grid-types-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Rotated](geodata_files/figure-html/fig-grid-types-2.png){#fig-grid-types-2 width=672}\n:::\n\n::: {.cell-output-display}\n![Sheared](geodata_files/figure-html/fig-grid-types-3.png){#fig-grid-types-3 width=672}\n:::\n\n::: {.cell-output-display}\n![Rectilinear](geodata_files/figure-html/fig-grid-types-4.png){#fig-grid-types-4 width=672}\n:::\n\n::: {.cell-output-display}\n![Curvilinear](geodata_files/figure-html/fig-grid-types-5.png){#fig-grid-types-5 width=672}\n:::\n\nMain types of raster data grids\n:::\n\n\nContrary to spatial vector data, a basic raster data stores just one attribute.\nIt is, however, possible to stack together many single rasters (also known as raster layers).\nThis allows us to store and operate on many rasters having the same dimensions at the same time.\nExamples of multi-layer rasters include satellite imageries or temporal rasters.\nSatellite imageries usually consist of many bands (layers) for different wavelengths.\nThe most basic bands, representing the colors red, green, and blue, can be connected together to create one composite image with true colors (@fig-rgb-raster).\nTemporal rasters store one attribute, but for many moments in time.\n<!-- + comparing different attributes for the same area -->\nAdditional information about multi-layer rasters can be also found in @sec-spatial-data-cubes.\n\n\n::: {#fig-rgb-raster .cell layout-ncol=\"4\"}\n::: {.cell-output-display}\n![Red](geodata_files/figure-html/fig-rgb-raster-1.png){#fig-rgb-raster-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Green](geodata_files/figure-html/fig-rgb-raster-2.png){#fig-rgb-raster-2 width=672}\n:::\n\n::: {.cell-output-display}\n![Blue](geodata_files/figure-html/fig-rgb-raster-3.png){#fig-rgb-raster-3 width=672}\n:::\n\n::: {.cell-output-display}\n![Composite](geodata_files/figure-html/fig-rgb-raster-4.png){#fig-rgb-raster-4 width=672}\n:::\n\nExample of three satellite imagery bands: red, green, blue, and the composite image with true colors created using these three bands.\n:::\n\n\n\\index{spatial file formats}\nSimilarly to vector data, a large number of raster file formats exists.\n<!-- text files ?-->\nCurrently, the GeoTIFF format (`.tif` or `.tiff`) is one of the most popular spatial raster formats.\nIt is an extended image TIF format that stores spatial metadata (e.g., map projection) along the values.\nAnother popular spatial raster formats include Arc ASCII (`.asc`) and ERDAS Imagine (`.img`).\n<!-- ncdf??? -->\n\n### Spatial data cubes {#sec-spatial-data-cubes}\n\n\\index{spatial data cubes}\nTraditionally, spatial vector and raster data models refer to a unique set of locations.\nFor example, each feature in a polygon dataset and each cell in a raster dataset refer to one specific area.\nHowever, to solve real-life problems, we need to store and operate on more complex data structures.\nIt includes situations when we have many attributes, often for several moments in time.\n\n\\index{spatial vector data cubes}\nStoring multiple attributes is not a problem for the vector data model, when an attribute table can have many columns.\nThe question is how to extend the spatial vector data model to include measurements for many times.\nFor example, let's consider a polygon data with many attributes representing shares of land-use types for several years (@fig-vector-data-cubes).\nOne approach would be to create a separate column for each variable in each year.<!--wide--><!--pros and cons-->\nAlternatively, we can have one column representing the year and one column for each attribute, however, this approach would require multiplying each geometry as many times as we have time stamps.\n<!--long--><!--pros and cons-->\nThe third approach involves separating geometries from attributes, and where attributes for each moment are stored independently.\nThe last idea is used in spatial vector data cubes (@sec-the-stars-package).\nAn example of the spatial vector data cubes idea can be seen in @fig-vector-data-cubes.\nIt consists of two elements: a geometry (MULTIPOLYGON) of provinces of the Netherlands and an array connected to it that stores shares of land-use types for several years. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Vector data cube.](geodata_files/figure-html/fig-vector-data-cubes-1.png){#fig-vector-data-cubes width=576}\n:::\n:::\n\n\n\\index{spatial raster data cubes}\nA single raster dataset can store just one variable for a given area.\nTo store several attributes, we can connect rasters representing different attributes for the same extent, creating multi-layer rasters (@sec-raster-data-model).\nAdditionally, each of the aforementioned rasters can be collected for many moments in time, adding other layers to the data.\n<!--pros and cons-->\nThe question here is how to efficiently store multi-layer raster data to understand what layers relate to which attribute and time.\nSimilarly to spatial vector data cubes, we can think of separating spatial dimensions from non-spatial attributes and create spatial raster data cubes (@sec-the-stars-package).\n@fig-raster-data-cubes gives an example of a raster data cube.\nIt consists of several single-layer rasters with the same spatial properties, such as resolution, extent, and CRS.\nThese rasters are organized to store four-dimensions of the data: latitude, longitude, time, and attributes.\nIt has values of three attributes for five moments in time in total.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Raster data cube.](geodata_files/figure-html/fig-raster-data-cubes-1.png){#fig-raster-data-cubes width=672}\n:::\n:::\n\n\nSpatial data cubes are suitable for many real-life applications.\nFor example, time-series of climate measurements for several stations, demographic data on a country level gathered for many years, or satellite imageries over some period of time.\n\n\\index{spatial file formats}\nOne way to create spatial data cubes is by connecting many independent vector or raster objects.\n<!-- mention it in the stars section? -->\nSecond way is to read a spatial data cube from one of the file formats allowing for storing complex data.\nIt includes formats such as NetCDF (`.nc`) and HDF (`.hdf`).\n<!-- spatial vector data cubes file formats? -->\n\n<!-- converting between spatial vector data cube and spatial raster data cube -->\n\n## Spatial data representations in R {#sec-spatial-data-representations-in-r}\n\n\\index{vector data model}\nR has several packages aimed to represent spatial vector data.\n<!-- Recently, the **terra** package has been released containing a new vector data representation. -->\nFor more than a decade, the **sp** package <!--REF--> was a standard of vector data representation in R.\nHowever, now this package is in the maintenance mode only, and its successor, **sf** is recommended.\nThe **tmap** package has been using **sf** since version 2.0.\n\n\\index{raster data model}\n\\index{spatial data cubes}\nSeveral R packages can be used to represent spatial raster data, including **raster** and its successor **terra**. \nThe **raster** package was used as a backbone of raster data visualization until **tmap** version 3.0.\nNowadays, the **stars** package is used by **tmap** to operate on raster data and spatial data cubes.\n\nIn the two next sections, we introduce the **sf** package (@sec-the-sf-package) and the **stars** package (@sec-the-stars-package).\n\n<!-- spatial data cubes -->\n<!-- https://github.com/appelmar/gdalcubes_R -->\n<!-- https://ropensci.org/blog/2019/11/05/tidync/ -->\n\n### The sf package {#sec-the-sf-package}\n\n\\index{sf}\n\\index{sf (package)|see {sf}}\n\nThe **sf** package implements ideas behind the Simple Feature standard, which describe how to represent spatial vector data.\nIts main class, `sf`, has the form of an extended data frame, where each row is a spatial feature.\nIn it, attributes of the vector data are stored as columns. \nIt also has one additional column, most often named `geom` or `geometry`^[However, any other names are also possible.].\nThis column contains geometries in a form of well-known text (WKT), storing all of the coordinates.\n\n<!-- - how to read sf objects from files -->\nThe **sf** package can read all of the spatial data formats mentioned in @sec-vector-data-model using the `read_sf()` function^[It is also possible to read spatial vector data using the `st_read()` function, which differs from `read_sf()` by having different default arguments.].\n<!--improve example-->\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nworldvector = read_sf(\"data/worldvector.gpkg\")\n```\n:::\n\n\nThe new object, `worldvector`, has a `sf` class. \nIt has 185 features (rows or geometries) and 15 fields (columns with attributes). \nThere is also an 16th column, `geom`, that stores geometries of each feature.\nObjects of class `sf` also display a header containing spatial metadata.\nIt includes geometry type, dimension (`XY`, `XYZ`, `XYM`, `XYZM`), bounding box (`bbox`), and information about the used Coordinate Reference System (`CRS`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworldvector\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 185 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -16331900 ymin: -8392908 xmax: 16886150 ymax: 8315884\nProjected CRS: WGS 84 / Equal Earth Greenwich\n# A tibble: 185 × 16\n   GEO   name    wb_region wb_income_region population CO2_emissions gdp_per_cap\n   <chr> <chr>   <chr>     <chr>                 <dbl>         <dbl>       <dbl>\n 1 AUS   Austra… East Asi… High income        42900000       15.3          56800\n 2 AZE   Azerba… Europe &… Upper middle in…    9190000        3.94          5770\n 3 BIH   Bosnia… Europe &… Upper middle in…    1640000        6.38          6030\n 4 BGD   Bangla… South As… Lower middle in…  151000000        0.474         1200\n 5 BEL   Belgium Europe &… High income        12500000        8.32         47200\n 6 BFA   Burkin… Sub-Saha… Low income         83200000        0.162          712\n 7 BGR   Bulgar… Europe &… Upper middle in…    3590000        5.85          8650\n 8 BDI   Burundi Sub-Saha… Low income         50900000        0.0447         211\n 9 BEN   Benin   Sub-Saha… Low income         47200000        0.614          897\n10 BRN   Brunei  East Asi… High income          390000       22.2          31400\n# ℹ 175 more rows\n# ℹ 9 more variables: life_expectancy <dbl>, corruption_perception_index <dbl>,\n#   democracy_score <dbl>, hdi <dbl>, energy_use_per_cap <dbl>,\n#   literacy_rate <dbl>, demo_corr <dbl>, demo_corr_rank <int>,\n#   geom <MULTIPOLYGON [m]>\n```\n\n\n:::\n:::\n\n\nThe `worldvector` object has MULTIPOLYGON geometry type, where each feature (row) can consist of one or more polygons.\nEach polygon's vertices are represented by a pair of values (`dimension: XY`).\nBounding box allows to quickly understand the spatial extension of the input data. \n<!--...--> \nFinally, it has projected CRS named WGS 84 / Equal Earth Greenwich.\nYou can learn more about Coordinate Reference Systems in @sec-crs.\n<!-- ref to CRS section -->\n\nSpatial vector data of class `sf` can be also obtained using some of other R data packages.\n<!-- add REFs--> \nFor example, **rnaturalearth** allows to download world map data, **osmdata** imports OpenStreetMap data as `sf` objects, and **tigris** loads TIGER/Line data.\n<!-- add reference to geocompr -->\n<!-- add reference to https://cran.r-project.org/web/views/Spatial.html (after my updates) -->\n\nThe **tmap** package accepts spatial vector data objects from both **sf** and **sp** packages.\nIn case of having vector objects in a different representation, they should be converted into `sf` objects first, before making maps.\nThe **sf** package has the `st_as_sf()` function that translates objects of many classes, including `Spatial` (from the **sp** package), `ppp`, `psp`, and `lpp` (from the **spatstat** package), to the objects of class `sf`.\nThe `st_as_sf()` function also allows to turn data frames into `sf` objects - the user needs to provide the input data frame, names of columns with coordinates, and additionally definition of the CRS of the data.\nFor example `my_sf = st_as_sf(my_df, coords = c(\"Xcolumn\", \"Ycolumn\"), crs = \"EPSG:4326\")`.\n\nIf you want to learn more about operating on `sf` objects, we recommend visiting the package website and vignettes at <https://r-spatial.github.io/sf/> and reading [the Geocomputation with R book](https://geocompr.github.io/) [@lovelace_geocomputation_2025].\n<!-- - vector simplification? -->\n\n### The stars package {#sec-the-stars-package}\n\n\\index{stars}\n\\index{stars (package)|see {stars}}\n\n<!-- intro stars -->\nThe **stars** package allows for reading and processing raster data in R. \nThis package also has support for both spatial vector and raster data cubes.\nIts main class, `stars`, is built as a list of matrices or arrays with metadata describing their dimensions.\nThe **stars** package is also well integrated with **sf**, with many `st_` functions (such as `st_crs()`) working also on `stars` objects.\n\n<!-- - how to read stars objects from files -->\nThe `read_stars()` function allow to read spatial raster data from a file^[The **stars** package also has a function `read_ncdf()` aimed at improved reading of NetCDF files.].\nThis function requires at least one argument with a filename to be read. \n<!--improve example-->\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stars)\nworldelevation = read_stars(\"data/worldelevation.tif\")\n```\n:::\n\n\nThe new object, `worldelevation`, is of a `stars` class. \nIt has two dimensions, `x` and `y`, and one attribute `worldelevation.tif`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworldelevation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstars object with 2 dimensions and 1 attribute\nattribute(s):\n                    Min. 1st Qu. Median     Mean 3rd Qu. Max.   NA's\nworldelevation.tif  -412     218    608 1139.982    1941 6410 389580\ndimension(s):\n  from   to offset   delta refsys point x/y\nx    1 1080   -180  0.3333 WGS 84 FALSE [x]\ny    1  540     90 -0.3333 WGS 84 FALSE [y]\n```\n\n\n:::\n:::\n\n\nThe `worldelevation.tif` attribute is a matrix, where each cell represents an elevation value.\nThe `x` dimension has 1080 elements (columns), starting from a coordinate (`offset`) of a cell boundary of `-180`. \nNext, the coordinates of further cells increase by `0.333333` (`delta`) - resolution in the `x` dimension.\nThe `y` dimension has 540 elements (rows), starting from a coordinate (`offset`) of a cell boundary of `90`. \nFor the `y` dimension, each further cell's coordinated decreases by `0.333333` (notice the negative value of `delta`) - resolution in the `y` dimension.\nBoth dimensions also have the same CRS - `WGS 84`.\n\n`read_stars()` also has several additional arguments including `RasterIO`, which gives control over the input data extent and resolution.\nFor example, the below code will read just the first and second bands (results not shown).\n<!-- - including reading chunks, changing resolution, and selecting bands -->\n<!--improve example-->\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_path3 = system.file(\"raster/landsat.tif\", package = \"spDataLarge\")\nx3 = read_stars(file_path3, RasterIO = list(bands = c(1, 2)))\n```\n:::\n\n\nInternally, a `stars` object is a list of `matrix` or `array` objects with additional attributes describing spatial metadata, such as a number of columns and rows, resolution, coordinate reference system, etc.\nAll of this information is read from the input file.\n\nStars objects are constructed by dimensions and attributes.\nDimensions relate to what kind of objects are stored as list elements. \nFor example, when it is a `matrix` then we just have two dimensions representing columns and rows.\nHowever, it is also possible to store multidimensional `array`s, which allow having many additional dimensions for bands, times, etc.\nAttributes, on the other hand, are stored as list elements.\nEach attribute can relate, for example to a different variable.\n\nReading a simple GeoTIFF file would result in having just two dimensions and one attribute (a `matrix`).\nOn the other hand, reading complex raster file formats, such as NetCDF could result in having more than two dimensions (e.g. time) and many attributes (e.g., an `array` with temperature, precipitation, humidity).\n<!-- how it relates to mapping? -->\n\n<!-- - stars proxy -->\n<!-- more than 1e8 cells to read -->\nBefore reading the file, the **stars** package checks if the input data is a curvilinear grid and what is the number of cells in the data.\nWhen the input data is small or curvilinear then the full data is read in computer memory.\nOtherwise, a `stars proxy` approach is used, where only metadata is read including pointers to where the complete data is.\nWhen we want to plot large raster data, then it is read at a lower resolution than the native one.\n<!-- ref to the section where we are explaining max.plot options -->\n\nThe **stars** package also has support for vector data cubes, where each geometry is just stored once (as a dimension), and each attribute is a `matrix` or an `array` with the number of rows equals to the number of geometries, the number of columns equals to another dimension (e.g., time), and possibly the number of `array` layers equals for additional dimensions.\n<!-- can we plot them in tmap? -->\n<!-- if so - there should be an example in the book + reference -->\n\n<!-- The **tmap** package accepts spatial raster data objects from both **stars** and **raster** packages. -->\n\nMore information on how the `stars` objects are organized and how to operate on them can be found in the **stars** package vignettes at https://r-spatial.github.io/stars. \n<!-- - advice: sometimes/often it is better to prepare spatial object before the mapping, than trying to over-customize the map -->\n\n## Map projections (CRS) {#sec-crs}\n\n<!-- intro -->\n\n### What are map projections? {#sec-crs-intro}\n\n\n::: {.cell}\n\n:::\n\n\n\\index{map projections}\nWe use maps so often in everyday life that most of us probably forget that a map is just a two-dimensional representation of a three-dimensional object, namely the earth.\nFor centuries, geographers and mathematicians wondered what the best way is to do this.\nLet us wonder with them for a second.\n\nThe world is shown as an orange below, not just to stimulate your appetite for this subject, but also since an orange peel is a good analogy for a two-dimensional map.\nA world map can be seen as an orange peel that is put flat on the table.\nThe question is how to do this.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![How to peel an orange?](images/orange_world.png){#fig-orange fig-scap='How to peel an orange?' width=606}\n:::\n:::\n\n\nWhen we peel the orange, ideally we want to rip the peel near areas of the earth that are less interesting. \nWhat is interesting depends on the application; for applications where land mass is more important than wetlands, it is a good idea to make the rips in the oceans.\nThe (interrupted) Goode homolosine projection, which is shown below, embodies this idea. \nAll continents and countries are preserved, except Antarctica and Greenland.\nThere is also a version of the Goode homolosine projection that focuses on preserving the oceans.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The (interrupted) Goode homolosine projection](geodata_files/figure-html/fig-crs-goode-1.png){#fig-crs-goode width=672}\n:::\n:::\n\n\nTo make the analogy between the orange peel and the surface of the earth complete, we have to assign two fictitious properties to the orange peel, namely that it is stretchable and deformable.\nThese properties are needed in order to make a non-interrupted map, as we will see in the next sections.\n\n\\index{map projections}\n\\index{coordinate reference system (CRS)}\nA method to flatten down the earth, for which the Goode homolosine projection shown in @fig-crs-goode is an example, is called a *map projection*. \nTechnically, it is also known as a *coordinate reference system* (*CRS*), which specifies the corresponding coordinate system, as well as the transformations to other map projections.\n\n### A model of the Earth {#sec-crs-earth}\n\n\\index{ellipsoid}\n<!--we should use either \"Earth\" or \"earth\" (both are right now in the text)-->\nThe orange and the Earth have another thing in common; both are spheres, but not perfect ones.\nThe Earth is metaphorically speaking a little fat: the circumference around the equator is 40,075 km whereas around the circumference that crosses both poles is 40,009 km.\n<!--source: https://en.wikipedia.org/wiki/Earth_physical_characteristics_tables-->\nTherefore, the earth can better be described as an ellipsoid.\nThe same applies to an orange; every orange is a little different, but probably very few oranges are perfect spheres.\n\nAlthough the ellipsoid is a good mathematical model to describe the earth's surface, keep in mind that the surface of the earth is not smooth;\nland mass usually lies on a higher altitude than sea level.\nWe could potentially map each point on the surface of the earth using a three-dimensional $(x, y, z)$ Cartesian coordinate system with the center of the mass of the Earth being the origin (0, 0, 0).\nHowever, since this has many mathematical complications, the ellipsoid is often sufficient as a model of the surface of the earth.\n\n\\index{datum}\nThis ellipsoid model and its translation to the Earth' surface is called a *(geodetic) datum*.\nThe most popular datum is WGS84, which has been introduced in 1984 as an international standard, and has been last revised in 2004.\nThere are many (slightly) different datums, which are often tailored for local applications.\nFor instance, NAD83, ETRS89, and GDA94 are slightly better models for North-America, Europe, and Australia respectively.\nHowever, since WGS84 is a very good approximation of the earth as a whole, it has been widely adopted worldwide and is also used by the Global Positioning System (GPS).\n\n\\index{latitude and longitude}\nWhen we have specified a datum, we are able to specify geographic locations with two familiar variables, namely *latitude* and *longitude*.\nThe latitude specifies the north-south position in degrees, where latitude = 0$^\\circ$ is the equator.\nThe latitudes for the north and south pole are 90$^\\circ$ and $-90^\\circ$ respectively.\nThe longitude specifies the east-west position in degrees, where by convention, the longitude = 0$^\\circ$ meridian crosses the Royal Observatory in Greenwich, UK.\nThe Longitude range is -180$^\\circ$ to 180$^\\circ$, and since this is a full circle, -180$^\\circ$ and $^\\circ$ specify the same longitude.\n\n\\index{graticule}\nWhen we see the earth in its three-dimensional form, as in @fig-orange, the latitude parallels are the horizontal lines around the earth, and the longitude meridians are the vertical lines around the earth.\nThe set of longitude meridians and latitude parallels is also referred to as *graticule*.\nIn all the figures in this section, latitude parallels are shown as gray lines for $-60^\\circ$, $-30^\\circ$, $0^\\circ$, $30^\\circ$ and $60^\\circ$, and longitude meridians from $-180^\\circ$ to $180^\\circ$ at every $30^\\circ$.\n\nPlease keep in mind that only a latitude and longitude are not sufficient to specify a geographic location.\nA datum is required.\nWhen people exchange latitude-longitude data, it is safe to assume that they implicitly have used the WGS84 datum.\nHowever, it is good practice to specify the datum explicitly.\n\n### Platte Carrée and Web Mercator {#sec-crs-projections}\n\n\\index{web mercator}\n\\index{EPSG}\nLet's take a closer look at two widely used map projections, namely the plain latitude-longitude coordinate system (using the WGS84 datum) and the Web Mercator projection, which is currently the de facto standard for interactive maps. \nThese projections are indexed as EPSG4326 and EPSG3857 respectively.\nEPSG is an institute that maintains a database of standard map projections.\n\n<!--https://geographx.co.nz/map-projections/-->\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Latitude longitude coordinates (EPSG 4326)](geodata_files/figure-html/fig-crs-04-1.png){#fig-crs-04 width=672}\n:::\n:::\n\n\nWhen we fictitiously make little holes in the orange peel at both poles, and stretch these open so wide that they have the same width as the equator, we obtain the cylinder depicted in @fig-crs-04 (left).\nNote that the longitude lines have become straight vertical lines.\nWhen we unroll this cylinder, we obtain a map where the $x$ and $y$ coordinates are the longitude and latitude respectively. \nThis CRS, which is known as EPSG4326, is shown in Figure @fig-crs-04 (right).\n\n\\index{coordinate reference system (CRS)}\n\\index{unprojected coordinate reference system (CRS)}\n\\index{projected coordinate reference system (CRS)}\nEPSG4326 is an *unprojected* CRS, since the longitude and latitude have not been transformed.\nWith *projected* CRSs, the $x$ and $y$ coordinates refer to specific measurement units, usually meters.\nThe projected variant of this CRS is called the *Platte Carrée* (EPSG4087), and is exactly the same map as shown in Figure @fig-crs-04 (right), but with other $x$ and $y$ value ranges.\n\nObserve since we stretched the poles open, the area near the poles have been stretched out as well.\nMore specifically, the closer the land is to one of the poles, the more it has been stretched out.\nSince the stretching direction is only horizontally, the shapes of the areas have become wider.\nA good example is Greenland, which is normally a 'tall' area (as can be seen in @fig-orange).\n\n\\index{web mercator}\nIn order to fix these deformed areas, Gerardus Mercator, a Flemish geographer in the 16th century introduced a method to compensate for this by inflating the areas near the poles even more, but now only in a vertical direction.\nThis projection is called the Mercator projection.\nFor web applications, this projection has been slightly modified and renamed to the Web Mercator projection (EPSG3857).\nThe cylinder and plain map that uses this projection are shown in @fig-crs-05.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Web Mercator projection (EPSG 3857)](geodata_files/figure-html/fig-crs-05-1.png){#fig-crs-05 width=672}\n:::\n:::\n\n\nAlthough the areas near the poles have been inflated quite a lot, especially Antarctica and Greenland, the shape of the areas is more or less correct, in particular regarding small areas (which can be seen by comparing with @fig-orange.\nThe Mercator projection is very useful for navigational purposes, and has therefore been embraced by sailors ever since.\nAlso today, the Web Mercator is the de facto standard for interactive maps and navigation services.\nHowever, for maps that show data the (Web) Mercator projection should be used with great caution, because the hugely inflated areas will influence how we perceive spatial data.\nWe will discuss this in the next section.\n\n### Types of map projections {#sec-proj-types}\n\n<!-- https://en.wikipedia.org/wiki/List_of_map_projections\nhttp://www.geog.uoregon.edu/shinker/geog311/Labs/lab02/properties.htm\nhttps://www.researchgate.net/publication/303311220_Projection_Wizard_-_An_Online_Map_Projection_Selection_Tool\nhttps://projectionwizard.org/\nhttps://kartoweb.itc.nl/geometrics/Map%20projections/body.htm\nhttp://www.geo.hunter.cuny.edu/~jochen/gtech201/lectures/lec6concepts/map%20coordinate%20systems/how%20to%20choose%20a%20projection.htm\nhttps://books.google.nl/books?id=E0JZDwAAQBAJ&pg=PA244&lpg=PA244&dq=Equidistant+projections+important&source=bl&ots=UqDt0ZBgEP&sig=ACfU3U3R1XN0i33v6Izh8fQZGJbpLF9ULw&hl=en&sa=X&ved=2ahUKEwi84tT_68rqAhUQ26QKHRcWD3AQ6AEwEHoECAgQAQ#v=onepage&q=Equidistant%20projections%20important&f=false\n-->\n\n\\index{map projections}\nLet us go back to the original question: how can we make a two-dimensional image of our three-dimensional earth? \nAlthough there are many ways, four basic map projection types can be distinguished. \nThese are depicted in @fig-crs-types.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Four types of map projections](geodata_files/figure-html/fig-crs-types-1.png){#fig-crs-types width=100%}\n:::\n:::\n\n\n\\index{cylindrical map projections}\nExamples for cylindrical projections have already been given in the previous section; both Platte Carrée and Web-Mercator are cylindrical. \nAnother widely used cylindrical map projection is the *Universal Transverse Mercator (UTM)*.\nThe cylinder is not placed upright, but horizontal.\nThere are 60 positions in which this cylinder can be placed, where in each position, the cylinder faces a longitude range of 6 degrees.\nIn other words the UTM is not a single projection, but a series of 60 projections.\n\nThere are many projections which are pseudo-cylinders in the sense that the radius around the poles is smaller than around the equator.\nAn example is the Robinson projection shown in @fig-crs-robin.\nAlmost all commonly used standard World map projections are (pseudo-)cylindrical.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The Robinson projection, which is pseudo-cylindrical.](geodata_files/figure-html/fig-crs-robin-1.png){#fig-crs-robin width=100%}\n:::\n:::\n\n\n\\index{conic map projections}\nAn example of a conic map projection is shown in @fig-crs-conic-planar-1.\nAs a result of unfolding a cone on a flat surface, a gap is created.\nThe size (angle) of this gap depends on the width of the cone.\nThere are also pseudo-conic map projections in which some meridians (longitude lines) are curved.\nConic map projections are useful for mid-latitude areas where the surfaces of the earth and the cone are almost parallel to each other. \n\n\\index{planar map projections}\nPlanar map projections, also known as azimuthal projections, project the Earth on a disk.\nThis can be done in several ways.\nThis can best be explained by the position of an imaginary light source.\nIt can be placed inside the globe, at the surface of the globe opposite to the disk, and at an infinite distance opposite to the disk.\nThe corresponding families of projections are called gnomonic, stereographic, and orthogonal projections.\n\nPlanar map projections are often used for a specific country or continent.\nAn example is the Lambert Azimuthal Equal-Area projection (EPSG3035), shown in @fig-crs-conic-planar-2, which is optimized for Europe.\nIt can be classified as a stereographic projection, although the light beams are not straight but curved.\nAnother example of a planar map projection is the orange shown in @fig-orange.\nThis is an orthogonal projection.\n\n\n::: {#fig-crs-conic-planar .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![World Equidistant Conic projection](geodata_files/figure-html/fig-crs-conic-planar-1.png){#fig-crs-conic-planar-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Lambert Azimuthal Equal-Area projection](geodata_files/figure-html/fig-crs-conic-planar-2.png){#fig-crs-conic-planar-2 width=672}\n:::\n\nExamples of a conic and a planar projection.\n:::\n\n\n\\index{interrupted map projections}\nThe (interrupted) Goode homolosine projection shown in @fig-crs-goode is an example of an interrupted projection.\nA special class of these projections are polyhedral projections, which consists of planar faces. \nIn @fig-crs-types a polyhedral of six faces is illustrated. \nThere is no limit of the number of faces, as the myriahedral projections (TODO reference Van Wijck paper) illustrate.\n\n### Which projection to choose? {#sec-crs-choose}\n\n\\index{map projections}\nHopefully it is clear that there is no perfect projection, since each projection has its pros and cons.\nWhether a projection is good for a certain application, depends on two factors.\nThe first factor is the type of application and in particular which map projection properties are useful or even required for that application.\nFor instance, navigation requires other map projection properties than statistical maps.\nThe second factor is the area of interest.\nIs the whole World visualized or only a part, and in the latter case, which part?\nIn this section, guidelines are provided to choose a proper projection based on those two aspects.\n\nBefore we go deeper into selecting a projection, it is worth noting that for many countries and continents, government agencies already have chosen projections to be the standard for mapping spatial data.\nFor instance, a standard for Europe, which is used by Eurostat (the statistical agency of the European Union), is the Lambert Azimuthal Equal-Area projection shown in @fig-crs-conic-planar-2.\nIf the area of interest has such a standard, it is recommended to use it, because it can be safely assumed that this standard is a proper projection, and moreover, it makes cooperation and communication with other parties easier.\nHowever, be aware of the limitations that this particular projection may have, and that there may be better alternatives out there.\n\n**Map projection properties**\n\n\\index{map projection: properties}\nThe type of application is important for the choice of a map projection.\nHowever, it would be quite tedious to list all possible applications and provide projection recommendations for each of them.\nInstead, we focus on four map projection properties.\nThe key step is to find out which of these properties are useful or even required for the target application.\nThe four properties are listed in the following table.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_934qahjlizssgcvjeytl(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_934qahjlizssgcvjeytl\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_934qahjlizssgcvjeytl');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_934qahjlizssgcvjeytl(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_934qahjlizssgcvjeytl\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 6, j: 1 }, { i: 6, j: 2 }, { i: 6, j: 3 }, { i: 6, j: 4 },  ], css_id: 'tinytable_css_sqt1gomokxkx3x9gbp13',}, \n          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 }, { i: 0, j: 3 }, { i: 0, j: 4 },  ], css_id: 'tinytable_css_phuumvda8df89tjkjx4f',}, \n          { positions: [ { i: 6, j: 0 },  ], css_id: 'tinytable_css_bzd2p2s0ikyqa1f9tb5o',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 },  ], css_id: 'tinytable_css_ehcmn3pch4uacvympdrf',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_m8vtu7l4uc0408hg1dcq',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_934qahjlizssgcvjeytl(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_sqt1gomokxkx3x9gbp13, .table th.tinytable_css_sqt1gomokxkx3x9gbp13 { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_phuumvda8df89tjkjx4f, .table th.tinytable_css_phuumvda8df89tjkjx4f { border-top: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_bzd2p2s0ikyqa1f9tb5o, .table th.tinytable_css_bzd2p2s0ikyqa1f9tb5o { font-weight: bold; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_ehcmn3pch4uacvympdrf, .table th.tinytable_css_ehcmn3pch4uacvympdrf { font-weight: bold; }\n      .table td.tinytable_css_m8vtu7l4uc0408hg1dcq, .table th.tinytable_css_m8vtu7l4uc0408hg1dcq { font-weight: bold; border-top: solid #d3d8dc 0.1em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_934qahjlizssgcvjeytl\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        <caption>Map projection properties.</caption>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td>Property</td>\n                  <td>Conformal</td>\n                  <td>Equal area</td>\n                  <td>Equidistant</td>\n                  <td>Azimuthal</td>\n                </tr>\n                <tr>\n                  <td>Preserves</td>\n                  <td>Local angle (shape)</td>\n                  <td>Area</td>\n                  <td>Distance</td>\n                  <td>Direction</td>\n                </tr>\n                <tr>\n                  <td>Applications</td>\n                  <td>Navigation, climate</td>\n                  <td>Statistics</td>\n                  <td>Geology</td>\n                  <td>Geology</td>\n                </tr>\n                <tr>\n                  <td>Examples (cyclindrical)</td>\n                  <td>Mercator</td>\n                  <td>Gall-Peters, Eckert IV</td>\n                  <td>Equirectangular</td>\n                  <td>none</td>\n                </tr>\n                <tr>\n                  <td>Examples (conic)</td>\n                  <td>Lambert conformal conic</td>\n                  <td>Albers conic</td>\n                  <td>Equidistant conic</td>\n                  <td>none</td>\n                </tr>\n                <tr>\n                  <td>Examples (planar)</td>\n                  <td>Stereographic</td>\n                  <td>Lambert azimuthal equal-area</td>\n                  <td>Azimuthal equidistant</td>\n                  <td>Stereographic, Lambert azimuthal equal-area</td>\n                </tr>\n                <tr>\n                  <td>Examples (interrupted)</td>\n                  <td>Myriahedral</td>\n                  <td>Goode homolosine, Myriahedral</td>\n                  <td>none</td>\n                  <td>none</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\\index{conformal map projections}\nA *conformal* projection means that local angles are preserved. \nIn practice, that means that for instance a map of a crossroad preserves the angles between the roads.\nTherefore, this property is required for navigational purposes.\nAs a consequence that local angles are preserved, local shapes are also preserved. \nThat means that an small island will be drawn on a map in its true shape, as seen from the sky perpendicular above it.\nThe Web Mercator shown in @fig-crs-05 satisfies this property; the closer an area is to one of the poles, the more it is enlarged, but since this is done in both dimensions (latitude and longitude), local shapes are preserved.\n\n\\index{equal-area map projections}\nA map projection is called *equal-area* if the areas are proportional to the true areas.\nThis is strongly recommended for maps that show statistics in order to prevent perceptual bias.\n@fig-crs-bias shows two World maps of population density per country, one in the Web Mercator projection and the other in Eckert IV projection.\nThe perception of World population is different in these maps; in (a) the vast lands on low-populated areas seem to be Canada, Greenland, and Russia, whereas in (b) also North Africa and Australia emerge as vast low-populated areas.\n\n\n::: {#fig-crs-bias .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Web Mercator is not equal-area](geodata_files/figure-html/fig-crs-bias-1.png){#fig-crs-bias-1 width=100%}\n:::\n\n::: {.cell-output-display}\n![Eckert IV is equal-area](geodata_files/figure-html/fig-crs-bias-2.png){#fig-crs-bias-2 width=100%}\n:::\n\nComparison of Web Mercator and Eckert IV projections.\n:::\n\n\n\\index{equidistant map projections}\n\\index{azimuthal map projections}\nThe other two map projection properties are related to one central point on the map.\nA map projection is called *equidistant* if the distances to any other point in the map are preserved, and *azimuthal* if the directions to any other point are preserved.\nThese properties are in particular useful in the field of geology.\nOne example is a seismic map around the epicenter of a recent earthquake, where it is important to how far and in which direction the vibrations are spreading.\n\n\\index{compromise map projections}\nA map projection can satisfy at most two of these properties. \nMany map projection do not satisfy any property but are intended as a compromise.\nAn example is the Robinson projection, shown in @fig-crs-robin.\n\n**Area of interest**\n\n\\index{map projection: area of interest}\nThe next aspect that is important for the choice of a map projection is the area of interest.\nIn general, the larger the area, the more concessions have to be made, since the larger the area, the more difficult it is to make a two-dimensional projection.\n\nThe following table provides recommendations of map projection types based on the area size and on the latitude of the area.\n\n\n::: {#tbl-crs-recommendations .cell}\n\n:::\n\n\nFor World maps, pseudo-cylindrical map projections, such as the Robinson projection (@fig-crs-robin) and the Eckert IV projection (@fig-crs-bias-2) are very popular because they have less distortion other map projections. \nFor areas that cover a half of the sphere, i.e. a hemisphere, azimuthal map projections are recommended. \nThere are four hemispheres that are often used: the Northern and Southern Hemisphere, with respectively the North and South Pole as center, the Western Hemisphere consisting of the Americas, and the Eastern Hemisphere, which includes the other continents. \nHowever, other hemispheres are often used implicitly, such as a hemisphere centered on Europe used in the Lambert Azimuthal Equal-Area projection shown in @fig-crs-conic-planar-2.\n\nFor areas with the size of a continent or country, the azimuthal map projection type can be used when centered on the area of interest.\nIn particular, the Lambert Azimuthal Equal-Area projection when equal area is required, and the Azimuthal Equidistant projection when preserving distances is important.\nAlternatively, cylindrical and conic map projection types can be used for areas at low and mid latitudes respectively.\nAnother alternative is to use a UTM projection.\nHowever, this is only recommended when the target area spans less than 6 degrees longitude.<!--and do not cross the UTM zone lines-->\n\n### CRS in R {#sec-crs-in-r}\n\n\\index{coordinate reference system (CRS)}\n\\index{PROJ}\nCoordinate Reference Systems (CRSs) are implemented in the software library [**PROJ**](https://proj.org/).\nWith implementation, we mean specifying a CRS and transforming coordinates from one CRS to another.\n**PROJ** is used by every popular software application for spatial data, in particular **ArcGIS**, **QGIS**, and **GRASS GIS**, and also by many programming languages, including R. \nThe **sf** package integrates the **PROJ** functions into R.   \n\nA CRS is represented in R by an object of class `crs`, which can be retrieved or set with the function `st_crs` (from the **sf** package).\nIn the following example, a `crs` object is created from an EPSG code, in this case 3035, the Lambert Azimuthal Equal-Area projection for Europe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\n# CRS Lambert Azimuthal Equal-Area projection\nst_crs(\"EPSG:3035\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3035 \n  wkt:\nPROJCRS[\"ETRS89-extended / LAEA Europe\",\n    BASEGEOGCRS[\"ETRS89\",\n        ENSEMBLE[\"European Terrestrial Reference System 1989 ensemble\",\n            MEMBER[\"European Terrestrial Reference Frame 1989\"],\n            MEMBER[\"European Terrestrial Reference Frame 1990\"],\n            MEMBER[\"European Terrestrial Reference Frame 1991\"],\n            MEMBER[\"European Terrestrial Reference Frame 1992\"],\n            MEMBER[\"European Terrestrial Reference Frame 1993\"],\n            MEMBER[\"European Terrestrial Reference Frame 1994\"],\n            MEMBER[\"European Terrestrial Reference Frame 1996\"],\n            MEMBER[\"European Terrestrial Reference Frame 1997\"],\n            MEMBER[\"European Terrestrial Reference Frame 2000\"],\n            MEMBER[\"European Terrestrial Reference Frame 2005\"],\n            MEMBER[\"European Terrestrial Reference Frame 2014\"],\n            MEMBER[\"European Terrestrial Reference Frame 2020\"],\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[0.1]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4258]],\n    CONVERSION[\"Europe Equal Area 2001\",\n        METHOD[\"Lambert Azimuthal Equal Area\",\n            ID[\"EPSG\",9820]],\n        PARAMETER[\"Latitude of natural origin\",52,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",10,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",4321000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",3210000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (Y)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (X)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Statistical analysis.\"],\n        AREA[\"Europe - European Union (EU) countries and candidates. Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Iceland; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal including Madeira and Azores; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain including Canary Islands; Sweden; Switzerland; Türkiye (Turkey); United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.\"],\n        BBOX[24.6,-35.58,84.73,44.83]],\n    ID[\"EPSG\",3035]]\n```\n\n\n:::\n:::\n\n\n\\index{crs objects}\nA `crs` object is represented by Well Known Text (WKT).\nIt includes a specification of the used datum as well as information how to transform it into other CRSs.\nUnderstanding the exact content of the WTK is not important for most users, since it is not needed to write a WKT yourself.\n\n\\index{crs objects}\n\\index{EPSG}\n\\index{proj4}\nA `crs` object can be created in several ways:\n<!--to improve in the future-->\n\n1. The first is with an EPSG number as user input specification as shown above. <!--it can be also some other \"provider\", e.g. \"ESRI:37001\"-->\n2. The second is also with a user input specification, but with a so-called *proj4* character string. \nThe *proj4* character string for the LAEA projection is `\"+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs\"`.\nHowever, *proj4* character strings should be used with caution since they often lack important CRS information regarding datums and CRS transformations.\nAlso note that the name *proj4* stands for the **PROJ** library version 4, while the current major version of **PROJ** at the time of writing is already 8.\n3. The third way is to provide some WKT definition of the projection. <!--...-->\n4. The last way to create a `crs` object is to extract it from an existing spatial data object (e.g., an **sf** or **stars** object) using the `st_crs()` function.\n\nA `crs` object can define a new spatial object's projection or transform an existing spatial object into another projection.\nIn the example below, we created a new object, `waterfalls`, with names and coordinates of three famous waterfalls.\nNext, we converted it into a spatial object of the `sf` class, `waterfalls_sf()` with `st_as_sf()`.\nWe can see that our object's coordinate reference system is not defined with the `st_crs()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a data.frame of three famous waterfalls\nwaterfalls = data.frame(name = c(\"Iguazu Falls\", \"Niagara Falls\", \"Victoria Falls\"), \n                        lat = c(-25.686785, 43.092461, -17.931805), \n                        lon = c(-54.444981, -79.047150, 25.825558))\n# create sf object (without specifying the crs)\nwaterfalls_sf = st_as_sf(waterfalls, coords = c(\"lon\", \"lat\"))\n# extract crs (not defined yet)\nst_crs(waterfalls_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System: NA\n```\n\n\n:::\n:::\n\n\nThis function also allows us to specify CRS of our object - in this example, coordinates of our object are in the WGS84 coordinate system, and thus we can use the EPSG code of 4326.\nWe can also confirmed that our operation was successful also using `st_crs()`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# specify crs\nst_crs(waterfalls_sf) = \"EPSG:4326\"\n# extract crs\nst_crs(waterfalls_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:4326 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n        MEMBER[\"World Geodetic System 1984 (Transit)\"],\n        MEMBER[\"World Geodetic System 1984 (G730)\"],\n        MEMBER[\"World Geodetic System 1984 (G873)\"],\n        MEMBER[\"World Geodetic System 1984 (G1150)\"],\n        MEMBER[\"World Geodetic System 1984 (G1674)\"],\n        MEMBER[\"World Geodetic System 1984 (G1762)\"],\n        MEMBER[\"World Geodetic System 1984 (G2139)\"],\n        MEMBER[\"World Geodetic System 1984 (G2296)\"],\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]],\n        ENSEMBLEACCURACY[2.0]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    USAGE[\n        SCOPE[\"Horizontal component of 3D system.\"],\n        AREA[\"World.\"],\n        BBOX[-90,-180,90,180]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n:::\n\n\nAlternatively, it is possible to set the CRS when creating a new `sf` object, as you can see below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwaterfalls_sf = st_as_sf(waterfalls, coords = c(\"lon\", \"lat\"), crs = \"EPSG:4326\")\n```\n:::\n\n\nThe `st_transform()` function is used to convert the existing spatial object's coordinates into another projection.\nFor example, let's transform our `waterfalls_sf` object to the Equal Earth projection (EPSG 8857).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwaterfalls_sf_trans = st_transform(waterfalls_sf, \"EPSG:8857\")\nwaterfalls_sf_trans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3 features and 1 field\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -6583123 ymin: -3244138 xmax: 2416945 ymax: 5261565\nProjected CRS: WGS 84 / Equal Earth Greenwich\n            name                  geometry\n1   Iguazu Falls POINT (-4969711 -3244138)\n2  Niagara Falls  POINT (-6583123 5261565)\n3 Victoria Falls  POINT (2416945 -2285044)\n```\n\n\n:::\n:::\n\n\n@fig-crs-trans-plot shows the data in the WGS84 coordinate system on the top and in the Equal Earth projection on the bottom.\nYou can see here that the decision of the projection used has an impact not only on the coordinates (notice the grid values), but also the continents' shapes.\n\n\n::: {#fig-crs-trans-plot .cell layout-nrow=\"2\"}\n::: {.cell-output-display}\n![WGS84 coordinate system](geodata_files/figure-html/fig-crs-trans-plot-1.png){#fig-crs-trans-plot-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Equal Earth projection](geodata_files/figure-html/fig-crs-trans-plot-2.png){#fig-crs-trans-plot-2 width=672}\n:::\n\nComparison between the same dataset of three waterfalls\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}